/* cpuprovider.c generated by valac 0.14.2, the Vala compiler
 * generated from cpuprovider.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <glibtop/cpu.h>
#include <float.h>
#include <math.h>


#define TYPE_PROVIDER (provider_get_type ())
#define PROVIDER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_PROVIDER, Provider))
#define PROVIDER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_PROVIDER, ProviderClass))
#define IS_PROVIDER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_PROVIDER))
#define IS_PROVIDER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_PROVIDER))
#define PROVIDER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_PROVIDER, ProviderClass))

typedef struct _Provider Provider;
typedef struct _ProviderClass ProviderClass;
typedef struct _ProviderPrivate ProviderPrivate;

#define TYPE_CPU_PROVIDER (cpu_provider_get_type ())
#define CPU_PROVIDER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_CPU_PROVIDER, CpuProvider))
#define CPU_PROVIDER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_CPU_PROVIDER, CpuProviderClass))
#define IS_CPU_PROVIDER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_CPU_PROVIDER))
#define IS_CPU_PROVIDER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_CPU_PROVIDER))
#define CPU_PROVIDER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_CPU_PROVIDER, CpuProviderClass))

typedef struct _CpuProvider CpuProvider;
typedef struct _CpuProviderClass CpuProviderClass;
typedef struct _CpuProviderPrivate CpuProviderPrivate;

struct _Provider {
	GObject parent_instance;
	ProviderPrivate * priv;
};

struct _ProviderClass {
	GObjectClass parent_class;
	void (*update) (Provider* self);
};

struct _CpuProvider {
	Provider parent_instance;
	CpuProviderPrivate * priv;
};

struct _CpuProviderClass {
	ProviderClass parent_class;
};

struct _CpuProviderPrivate {
	guint64* lastdata;
	gint lastdata_length1;
	gint _lastdata_size_;
};


static gpointer cpu_provider_parent_class = NULL;

GType provider_get_type (void) G_GNUC_CONST;
GType cpu_provider_get_type (void) G_GNUC_CONST;
#define CPU_PROVIDER_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_CPU_PROVIDER, CpuProviderPrivate))
enum  {
	CPU_PROVIDER_DUMMY_PROPERTY
};
CpuProvider* cpu_provider_new (void);
CpuProvider* cpu_provider_construct (GType object_type);
Provider* provider_construct (GType object_type, const gchar* id, gchar** keys, int keys_length1);
static void cpu_provider_real_update (Provider* base);
gdouble* provider_get_values (Provider* self, int* result_length1);
static guint64* _vala_array_dup1 (guint64* self, int length);
static void cpu_provider_finalize (GObject* obj);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);


CpuProvider* cpu_provider_construct (GType object_type) {
	CpuProvider * self = NULL;
	gchar* _tmp0_;
	gchar* _tmp1_;
	gchar* _tmp2_;
	gchar* _tmp3_;
	gchar* _tmp4_;
	gchar* _tmp5_;
	gchar** _tmp6_ = NULL;
	gchar** _tmp7_;
	gint _tmp7__length1;
	_tmp0_ = g_strdup ("user");
	_tmp1_ = g_strdup ("sys");
	_tmp2_ = g_strdup ("nice");
	_tmp3_ = g_strdup ("idle");
	_tmp4_ = g_strdup ("io");
	_tmp5_ = g_strdup ("inuse");
	_tmp6_ = g_new0 (gchar*, 6 + 1);
	_tmp6_[0] = _tmp0_;
	_tmp6_[1] = _tmp1_;
	_tmp6_[2] = _tmp2_;
	_tmp6_[3] = _tmp3_;
	_tmp6_[4] = _tmp4_;
	_tmp6_[5] = _tmp5_;
	_tmp7_ = _tmp6_;
	_tmp7__length1 = 6;
	self = (CpuProvider*) provider_construct (object_type, "cpu", _tmp7_, 6);
	_tmp7_ = (_vala_array_free (_tmp7_, _tmp7__length1, (GDestroyNotify) g_free), NULL);
	return self;
}


CpuProvider* cpu_provider_new (void) {
	return cpu_provider_construct (TYPE_CPU_PROVIDER);
}


static guint64* _vala_array_dup1 (guint64* self, int length) {
	return g_memdup (self, length * sizeof (guint64));
}


static void cpu_provider_real_update (Provider* base) {
	CpuProvider * self;
	glibtop_cpu cpu = {0};
	glibtop_cpu _tmp0_ = {0};
	guint64* _tmp1_ = NULL;
	guint64* newdata;
	gint newdata_length1;
	gint _newdata_size_;
	guint64* _tmp2_;
	gint _tmp2__length1;
	glibtop_cpu _tmp3_;
	guint64 _tmp4_;
	guint64 _tmp5_;
	guint64* _tmp6_;
	gint _tmp6__length1;
	glibtop_cpu _tmp7_;
	guint64 _tmp8_;
	guint64 _tmp9_;
	guint64* _tmp10_;
	gint _tmp10__length1;
	glibtop_cpu _tmp11_;
	guint64 _tmp12_;
	guint64 _tmp13_;
	guint64* _tmp14_;
	gint _tmp14__length1;
	glibtop_cpu _tmp15_;
	guint64 _tmp16_;
	guint64 _tmp17_;
	guint64* _tmp18_;
	gint _tmp18__length1;
	glibtop_cpu _tmp19_;
	guint64 _tmp20_;
	glibtop_cpu _tmp21_;
	guint64 _tmp22_;
	glibtop_cpu _tmp23_;
	guint64 _tmp24_;
	guint64 _tmp25_;
	guint64* _tmp26_;
	gint _tmp26__length1;
	glibtop_cpu _tmp27_;
	guint64 _tmp28_;
	glibtop_cpu _tmp29_;
	guint64 _tmp30_;
	glibtop_cpu _tmp31_;
	guint64 _tmp32_;
	guint64 _tmp33_;
	gdouble total;
	guint64* _tmp34_;
	gint _tmp34__length1;
	guint64* _tmp63_;
	gint _tmp63__length1;
	guint64* _tmp64_;
	gint _tmp64__length1;
	self = CPU_PROVIDER (base);
	glibtop_get_cpu (&_tmp0_);
	cpu = _tmp0_;
	_tmp1_ = g_new0 (guint64, 6);
	newdata = _tmp1_;
	newdata_length1 = 6;
	_newdata_size_ = newdata_length1;
	_tmp2_ = newdata;
	_tmp2__length1 = newdata_length1;
	_tmp3_ = cpu;
	_tmp4_ = _tmp3_.user;
	_tmp2_[0] = _tmp4_;
	_tmp5_ = _tmp2_[0];
	_tmp6_ = newdata;
	_tmp6__length1 = newdata_length1;
	_tmp7_ = cpu;
	_tmp8_ = _tmp7_.sys;
	_tmp6_[1] = _tmp8_;
	_tmp9_ = _tmp6_[1];
	_tmp10_ = newdata;
	_tmp10__length1 = newdata_length1;
	_tmp11_ = cpu;
	_tmp12_ = _tmp11_.nice;
	_tmp10_[2] = _tmp12_;
	_tmp13_ = _tmp10_[2];
	_tmp14_ = newdata;
	_tmp14__length1 = newdata_length1;
	_tmp15_ = cpu;
	_tmp16_ = _tmp15_.idle;
	_tmp14_[3] = _tmp16_;
	_tmp17_ = _tmp14_[3];
	_tmp18_ = newdata;
	_tmp18__length1 = newdata_length1;
	_tmp19_ = cpu;
	_tmp20_ = _tmp19_.iowait;
	_tmp21_ = cpu;
	_tmp22_ = _tmp21_.irq;
	_tmp23_ = cpu;
	_tmp24_ = _tmp23_.softirq;
	_tmp18_[4] = (_tmp20_ + _tmp22_) + _tmp24_;
	_tmp25_ = _tmp18_[4];
	_tmp26_ = newdata;
	_tmp26__length1 = newdata_length1;
	_tmp27_ = cpu;
	_tmp28_ = _tmp27_.user;
	_tmp29_ = cpu;
	_tmp30_ = _tmp29_.nice;
	_tmp31_ = cpu;
	_tmp32_ = _tmp31_.sys;
	_tmp26_[5] = (_tmp28_ + _tmp30_) + _tmp32_;
	_tmp33_ = _tmp26_[5];
	total = (gdouble) 0;
	_tmp34_ = self->priv->lastdata;
	_tmp34__length1 = self->priv->lastdata_length1;
	if (_tmp34__length1 != 0) {
		{
			guint i;
			i = (guint) 0;
			{
				gboolean _tmp35_;
				_tmp35_ = TRUE;
				while (TRUE) {
					gboolean _tmp36_;
					guint _tmp38_;
					gdouble _tmp39_;
					guint64* _tmp40_;
					gint _tmp40__length1;
					guint _tmp41_;
					guint64 _tmp42_;
					guint64* _tmp43_;
					gint _tmp43__length1;
					guint _tmp44_;
					guint64 _tmp45_;
					_tmp36_ = _tmp35_;
					if (!_tmp36_) {
						guint _tmp37_;
						_tmp37_ = i;
						i = _tmp37_ + 1;
					}
					_tmp35_ = FALSE;
					_tmp38_ = i;
					if (!(_tmp38_ < ((guint) 5))) {
						break;
					}
					_tmp39_ = total;
					_tmp40_ = newdata;
					_tmp40__length1 = newdata_length1;
					_tmp41_ = i;
					_tmp42_ = _tmp40_[_tmp41_];
					_tmp43_ = self->priv->lastdata;
					_tmp43__length1 = self->priv->lastdata_length1;
					_tmp44_ = i;
					_tmp45_ = _tmp43_[_tmp44_];
					total = _tmp39_ + (_tmp42_ - _tmp45_);
				}
			}
		}
		{
			guint i;
			guint64* _tmp46_;
			gint _tmp46__length1;
			guint isize;
			i = (guint) 0;
			_tmp46_ = newdata;
			_tmp46__length1 = newdata_length1;
			isize = (guint) _tmp46__length1;
			{
				gboolean _tmp47_;
				_tmp47_ = TRUE;
				while (TRUE) {
					gboolean _tmp48_;
					guint _tmp50_;
					guint _tmp51_;
					gdouble* _tmp52_;
					gint _tmp52__length1;
					gdouble* _tmp53_;
					gint _tmp53__length1;
					guint _tmp54_;
					guint64* _tmp55_;
					gint _tmp55__length1;
					guint _tmp56_;
					guint64 _tmp57_;
					guint64* _tmp58_;
					gint _tmp58__length1;
					guint _tmp59_;
					guint64 _tmp60_;
					gdouble _tmp61_;
					gdouble _tmp62_;
					_tmp48_ = _tmp47_;
					if (!_tmp48_) {
						guint _tmp49_;
						_tmp49_ = i;
						i = _tmp49_ + 1;
					}
					_tmp47_ = FALSE;
					_tmp50_ = i;
					_tmp51_ = isize;
					if (!(_tmp50_ < _tmp51_)) {
						break;
					}
					_tmp52_ = provider_get_values (PROVIDER (self), &_tmp52__length1);
					_tmp53_ = _tmp52_;
					_tmp53__length1 = _tmp52__length1;
					_tmp54_ = i;
					_tmp55_ = newdata;
					_tmp55__length1 = newdata_length1;
					_tmp56_ = i;
					_tmp57_ = _tmp55_[_tmp56_];
					_tmp58_ = self->priv->lastdata;
					_tmp58__length1 = self->priv->lastdata_length1;
					_tmp59_ = i;
					_tmp60_ = _tmp58_[_tmp59_];
					_tmp61_ = total;
					_tmp53_[_tmp54_] = (_tmp57_ - _tmp60_) / _tmp61_;
					_tmp62_ = _tmp53_[_tmp54_];
				}
			}
		}
	}
	_tmp63_ = newdata;
	_tmp63__length1 = newdata_length1;
	_tmp64_ = (_tmp63_ != NULL) ? _vala_array_dup1 (_tmp63_, _tmp63__length1) : ((gpointer) _tmp63_);
	_tmp64__length1 = _tmp63__length1;
	self->priv->lastdata = (g_free (self->priv->lastdata), NULL);
	self->priv->lastdata = _tmp64_;
	self->priv->lastdata_length1 = _tmp64__length1;
	self->priv->_lastdata_size_ = self->priv->lastdata_length1;
	newdata = (g_free (newdata), NULL);
}


static void cpu_provider_class_init (CpuProviderClass * klass) {
	cpu_provider_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (CpuProviderPrivate));
	PROVIDER_CLASS (klass)->update = cpu_provider_real_update;
	G_OBJECT_CLASS (klass)->finalize = cpu_provider_finalize;
}


static void cpu_provider_instance_init (CpuProvider * self) {
	self->priv = CPU_PROVIDER_GET_PRIVATE (self);
}


static void cpu_provider_finalize (GObject* obj) {
	CpuProvider * self;
	self = CPU_PROVIDER (obj);
	self->priv->lastdata = (g_free (self->priv->lastdata), NULL);
	G_OBJECT_CLASS (cpu_provider_parent_class)->finalize (obj);
}


/******************************************************************************
 * Copyright (C) 2011  Michael Hofmann <mh21@piware.de>                       *
 *                                                                            *
 * This program is free software; you can redistribute it and/or modify       *
 * it under the terms of the GNU General Public License as published by       *
 * the Free Software Foundation; either version 3 of the License, or          *
 * (at your option) any later version.                                        *
 *                                                                            *
 * This program is distributed in the hope that it will be useful,            *
 * but WITHOUT ANY WARRANTY; without even the implied warranty of             *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the              *
 * GNU General Public License for more details.                               *
 *                                                                            *
 * You should have received a copy of the GNU General Public License along    *
 * with this program; if not, write to the Free Software Foundation, Inc.,    *
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.                *
 ******************************************************************************/
GType cpu_provider_get_type (void) {
	static volatile gsize cpu_provider_type_id__volatile = 0;
	if (g_once_init_enter (&cpu_provider_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (CpuProviderClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) cpu_provider_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (CpuProvider), 0, (GInstanceInitFunc) cpu_provider_instance_init, NULL };
		GType cpu_provider_type_id;
		cpu_provider_type_id = g_type_register_static (TYPE_PROVIDER, "CpuProvider", &g_define_type_info, 0);
		g_once_init_leave (&cpu_provider_type_id__volatile, cpu_provider_type_id);
	}
	return cpu_provider_type_id__volatile;
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}



