/* itempreferences.c generated by valac 0.14.2, the Vala compiler
 * generated from itempreferences.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <gio/gio.h>
#include <stdlib.h>
#include <string.h>


#define TYPE_ITEM_PREFERENCES (item_preferences_get_type ())
#define ITEM_PREFERENCES(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_ITEM_PREFERENCES, ItemPreferences))
#define ITEM_PREFERENCES_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_ITEM_PREFERENCES, ItemPreferencesClass))
#define IS_ITEM_PREFERENCES(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_ITEM_PREFERENCES))
#define IS_ITEM_PREFERENCES_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_ITEM_PREFERENCES))
#define ITEM_PREFERENCES_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_ITEM_PREFERENCES, ItemPreferencesClass))

typedef struct _ItemPreferences ItemPreferences;
typedef struct _ItemPreferencesClass ItemPreferencesClass;
typedef struct _ItemPreferencesPrivate ItemPreferencesPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))

#define TYPE_SETTINGS_CACHE (settings_cache_get_type ())
#define SETTINGS_CACHE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_SETTINGS_CACHE, SettingsCache))
#define SETTINGS_CACHE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_SETTINGS_CACHE, SettingsCacheClass))
#define IS_SETTINGS_CACHE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_SETTINGS_CACHE))
#define IS_SETTINGS_CACHE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_SETTINGS_CACHE))
#define SETTINGS_CACHE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_SETTINGS_CACHE, SettingsCacheClass))

typedef struct _SettingsCache SettingsCache;
typedef struct _SettingsCacheClass SettingsCacheClass;
#define _gtk_tree_path_free0(var) ((var == NULL) ? NULL : (var = (gtk_tree_path_free (var), NULL)))

struct _ItemPreferences {
	GObject parent_instance;
	ItemPreferencesPrivate * priv;
};

struct _ItemPreferencesClass {
	GObjectClass parent_class;
};

struct _ItemPreferencesPrivate {
	GtkDialog* items;
	GtkListStore* itemstore;
	GtkTreeView* itemview;
	GtkTreeSelection* itemselection;
	GtkButton* itemadd;
	GtkButton* itemremove;
	GtkButton* itemedit;
	GtkButton* itemup;
	GtkButton* itemdown;
	GSettings* itemsettings;
	gboolean itemsignoresignals;
	gchar* _settingskey;
};


static gpointer item_preferences_parent_class = NULL;

GType item_preferences_get_type (void) G_GNUC_CONST;
#define ITEM_PREFERENCES_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_ITEM_PREFERENCES, ItemPreferencesPrivate))
enum  {
	ITEM_PREFERENCES_DUMMY_PROPERTY,
	ITEM_PREFERENCES_SETTINGSKEY
};
ItemPreferences* item_preferences_new (const gchar* settingskey);
ItemPreferences* item_preferences_construct (GType object_type, const gchar* settingskey);
void item_preferences_show (ItemPreferences* self);
GObject* utils_get_ui (const gchar* objectid, GObject* signalhandlers, gchar** additional, int additional_length1, GtkBuilder** builder);
SettingsCache* settings_cache_new (void);
SettingsCache* settings_cache_construct (GType object_type);
GType settings_cache_get_type (void) G_GNUC_CONST;
GSettings* settings_cache_generalsettings (SettingsCache* self);
void item_preferences_on_itemsettings_changed (ItemPreferences* self);
static void _item_preferences_on_itemsettings_changed_g_settings_changed (GSettings* _sender, const gchar* key, gpointer self);
void item_preferences_on_itemselection_changed (ItemPreferences* self);
static void _item_preferences_on_itemselection_changed_gtk_tree_selection_changed (GtkTreeSelection* _sender, gpointer self);
static void item_preferences_itemsgsettingstostore (ItemPreferences* self);
void item_preferences_on_itemdialog_destroy (GtkWidget* source, ItemPreferences* self);
void item_preferences_on_itemdialog_response (GtkDialog* source, gint response, ItemPreferences* self);
const gchar* item_preferences_get_settingskey (ItemPreferences* self);
void item_preferences_on_expressionrenderer_edited (GtkCellRendererText* renderer, const gchar* path, const gchar* new_text, ItemPreferences* self);
static void item_preferences_updatebuttons (ItemPreferences* self);
void item_preferences_on_itemstore_row_inserted (GtkTreeModel* model, const gchar* path, GtkTreeIter* iter, ItemPreferences* self);
static void item_preferences_itemsstoretogsettings (ItemPreferences* self);
void item_preferences_on_itemstore_row_changed (GtkTreeModel* model, const gchar* path, GtkTreeIter* iter, ItemPreferences* self);
void item_preferences_on_itemstore_row_deleted (GtkTreeModel* model, const gchar* path, ItemPreferences* self);
void item_preferences_on_itemadd_clicked (GtkButton* button, ItemPreferences* self);
void item_preferences_on_itemremove_clicked (GtkButton* button, ItemPreferences* self);
void item_preferences_on_itemedit_clicked (GtkButton* button, ItemPreferences* self);
void item_preferences_on_itemup_clicked (GtkButton* button, ItemPreferences* self);
void item_preferences_on_itemdown_clicked (GtkButton* button, ItemPreferences* self);
static void item_preferences_set_settingskey (ItemPreferences* self, const gchar* value);
static void item_preferences_finalize (GObject* obj);
static void _vala_item_preferences_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_item_preferences_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);
static gint _vala_array_length (gpointer array);


ItemPreferences* item_preferences_construct (GType object_type, const gchar* settingskey) {
	ItemPreferences * self = NULL;
	const gchar* _tmp0_;
	g_return_val_if_fail (settingskey != NULL, NULL);
	_tmp0_ = settingskey;
	self = (ItemPreferences*) g_object_new (object_type, "settingskey", _tmp0_, NULL);
	return self;
}


ItemPreferences* item_preferences_new (const gchar* settingskey) {
	return item_preferences_construct (TYPE_ITEM_PREFERENCES, settingskey);
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


static void _item_preferences_on_itemsettings_changed_g_settings_changed (GSettings* _sender, const gchar* key, gpointer self) {
	item_preferences_on_itemsettings_changed (self);
}


static void _item_preferences_on_itemselection_changed_gtk_tree_selection_changed (GtkTreeSelection* _sender, gpointer self) {
	item_preferences_on_itemselection_changed (self);
}


void item_preferences_show (ItemPreferences* self) {
	GtkDialog* _tmp0_;
	GtkBuilder* builder = NULL;
	gchar* _tmp2_;
	gchar** _tmp3_ = NULL;
	gchar** _tmp4_;
	gint _tmp4__length1;
	GtkBuilder* _tmp5_ = NULL;
	GObject* _tmp6_ = NULL;
	GtkDialog* _tmp7_;
	GtkBuilder* _tmp8_;
	GObject* _tmp9_ = NULL;
	GtkListStore* _tmp10_;
	GtkBuilder* _tmp11_;
	GObject* _tmp12_ = NULL;
	GtkTreeView* _tmp13_;
	SettingsCache* _tmp14_;
	SettingsCache* _tmp15_;
	GSettings* _tmp16_ = NULL;
	GSettings* _tmp17_;
	GtkBuilder* _tmp18_;
	GObject* _tmp19_ = NULL;
	GtkButton* _tmp20_;
	GtkBuilder* _tmp21_;
	GObject* _tmp22_ = NULL;
	GtkButton* _tmp23_;
	GtkBuilder* _tmp24_;
	GObject* _tmp25_ = NULL;
	GtkButton* _tmp26_;
	GtkBuilder* _tmp27_;
	GObject* _tmp28_ = NULL;
	GtkButton* _tmp29_;
	GtkBuilder* _tmp30_;
	GObject* _tmp31_ = NULL;
	GtkButton* _tmp32_;
	GtkBuilder* _tmp33_;
	GObject* _tmp34_ = NULL;
	GtkTreeSelection* _tmp35_ = NULL;
	GtkTreeSelection* _tmp36_;
	GtkTreeSelection* _tmp37_;
	GtkTreeSelection* _tmp38_;
	GtkTreePath* _tmp39_;
	GtkTreePath* _tmp40_;
	GtkDialog* _tmp41_;
	g_return_if_fail (IS_ITEM_PREFERENCES (self));
	_tmp0_ = self->priv->items;
	if (_tmp0_ != NULL) {
		GtkDialog* _tmp1_;
		_tmp1_ = self->priv->items;
		gtk_window_present (GTK_WINDOW (_tmp1_));
		return;
	}
	_tmp2_ = g_strdup ("itemstore");
	_tmp3_ = g_new0 (gchar*, 1 + 1);
	_tmp3_[0] = _tmp2_;
	_tmp4_ = _tmp3_;
	_tmp4__length1 = 1;
	_tmp6_ = utils_get_ui ("itemdialog", G_OBJECT (self), _tmp4_, 1, &_tmp5_);
	_g_object_unref0 (builder);
	builder = _tmp5_;
	_g_object_unref0 (self->priv->items);
	self->priv->items = GTK_IS_DIALOG (_tmp6_) ? ((GtkDialog*) _tmp6_) : NULL;
	_tmp4_ = (_vala_array_free (_tmp4_, _tmp4__length1, (GDestroyNotify) g_free), NULL);
	_tmp7_ = self->priv->items;
	g_return_if_fail (_tmp7_ != NULL);
	_tmp8_ = builder;
	_tmp9_ = gtk_builder_get_object (_tmp8_, "itemstore");
	_tmp10_ = _g_object_ref0 (GTK_IS_LIST_STORE (_tmp9_) ? ((GtkListStore*) _tmp9_) : NULL);
	_g_object_unref0 (self->priv->itemstore);
	self->priv->itemstore = _tmp10_;
	_tmp11_ = builder;
	_tmp12_ = gtk_builder_get_object (_tmp11_, "itemview");
	_tmp13_ = _g_object_ref0 (GTK_IS_TREE_VIEW (_tmp12_) ? ((GtkTreeView*) _tmp12_) : NULL);
	_g_object_unref0 (self->priv->itemview);
	self->priv->itemview = _tmp13_;
	_tmp14_ = settings_cache_new ();
	_tmp15_ = _tmp14_;
	_tmp16_ = settings_cache_generalsettings (_tmp15_);
	_g_object_unref0 (self->priv->itemsettings);
	self->priv->itemsettings = _tmp16_;
	_g_object_unref0 (_tmp15_);
	_tmp17_ = self->priv->itemsettings;
	g_signal_connect_object (_tmp17_, "changed::menu-expressions", (GCallback) _item_preferences_on_itemsettings_changed_g_settings_changed, self, 0);
	_tmp18_ = builder;
	_tmp19_ = gtk_builder_get_object (_tmp18_, "itemadd");
	_tmp20_ = _g_object_ref0 (GTK_IS_BUTTON (_tmp19_) ? ((GtkButton*) _tmp19_) : NULL);
	_g_object_unref0 (self->priv->itemadd);
	self->priv->itemadd = _tmp20_;
	_tmp21_ = builder;
	_tmp22_ = gtk_builder_get_object (_tmp21_, "itemremove");
	_tmp23_ = _g_object_ref0 (GTK_IS_BUTTON (_tmp22_) ? ((GtkButton*) _tmp22_) : NULL);
	_g_object_unref0 (self->priv->itemremove);
	self->priv->itemremove = _tmp23_;
	_tmp24_ = builder;
	_tmp25_ = gtk_builder_get_object (_tmp24_, "itemedit");
	_tmp26_ = _g_object_ref0 (GTK_IS_BUTTON (_tmp25_) ? ((GtkButton*) _tmp25_) : NULL);
	_g_object_unref0 (self->priv->itemedit);
	self->priv->itemedit = _tmp26_;
	_tmp27_ = builder;
	_tmp28_ = gtk_builder_get_object (_tmp27_, "itemup");
	_tmp29_ = _g_object_ref0 (GTK_IS_BUTTON (_tmp28_) ? ((GtkButton*) _tmp28_) : NULL);
	_g_object_unref0 (self->priv->itemup);
	self->priv->itemup = _tmp29_;
	_tmp30_ = builder;
	_tmp31_ = gtk_builder_get_object (_tmp30_, "itemdown");
	_tmp32_ = _g_object_ref0 (GTK_IS_BUTTON (_tmp31_) ? ((GtkButton*) _tmp31_) : NULL);
	_g_object_unref0 (self->priv->itemdown);
	self->priv->itemdown = _tmp32_;
	_tmp33_ = builder;
	_tmp34_ = gtk_builder_get_object (_tmp33_, "itemview");
	_tmp35_ = gtk_tree_view_get_selection (GTK_IS_TREE_VIEW (_tmp34_) ? ((GtkTreeView*) _tmp34_) : NULL);
	_tmp36_ = _g_object_ref0 (_tmp35_);
	_g_object_unref0 (self->priv->itemselection);
	self->priv->itemselection = _tmp36_;
	_tmp37_ = self->priv->itemselection;
	g_signal_connect_object (_tmp37_, "changed", (GCallback) _item_preferences_on_itemselection_changed_gtk_tree_selection_changed, self, 0);
	item_preferences_itemsgsettingstostore (self);
	_tmp38_ = self->priv->itemselection;
	_tmp39_ = gtk_tree_path_new_from_indices (0, -1);
	_tmp40_ = _tmp39_;
	gtk_tree_selection_select_path (_tmp38_, _tmp40_);
	_gtk_tree_path_free0 (_tmp40_);
	_tmp41_ = self->priv->items;
	gtk_widget_show_all (GTK_WIDGET (_tmp41_));
	_g_object_unref0 (builder);
}


void item_preferences_on_itemdialog_destroy (GtkWidget* source, ItemPreferences* self) {
	g_return_if_fail (IS_ITEM_PREFERENCES (self));
	g_return_if_fail (GTK_IS_WIDGET (source));
	_g_object_unref0 (self->priv->items);
	self->priv->items = NULL;
	_g_object_unref0 (self->priv->itemstore);
	self->priv->itemstore = NULL;
	_g_object_unref0 (self->priv->itemsettings);
	self->priv->itemsettings = NULL;
}


void item_preferences_on_itemdialog_response (GtkDialog* source, gint response, ItemPreferences* self) {
	gint _tmp0_;
	GSettings* _tmp2_;
	const gchar* _tmp3_;
	GtkTreeSelection* _tmp4_;
	GtkTreePath* _tmp5_;
	GtkTreePath* _tmp6_;
	g_return_if_fail (IS_ITEM_PREFERENCES (self));
	g_return_if_fail (GTK_IS_DIALOG (source));
	_tmp0_ = response;
	if (_tmp0_ != 1) {
		GtkDialog* _tmp1_;
		_tmp1_ = source;
		gtk_widget_destroy (GTK_WIDGET (_tmp1_));
		return;
	}
	_tmp2_ = self->priv->itemsettings;
	_tmp3_ = self->priv->_settingskey;
	g_settings_reset (_tmp2_, _tmp3_);
	_tmp4_ = self->priv->itemselection;
	_tmp5_ = gtk_tree_path_new_from_indices (0, -1);
	_tmp6_ = _tmp5_;
	gtk_tree_selection_select_path (_tmp4_, _tmp6_);
	_gtk_tree_path_free0 (_tmp6_);
}


void item_preferences_on_expressionrenderer_edited (GtkCellRendererText* renderer, const gchar* path, const gchar* new_text, ItemPreferences* self) {
	GtkTreeIter iter = {0};
	GtkListStore* _tmp0_;
	const gchar* _tmp1_;
	GtkTreeIter _tmp2_ = {0};
	GtkListStore* _tmp3_;
	GtkTreeIter _tmp4_;
	const gchar* _tmp5_;
	g_return_if_fail (IS_ITEM_PREFERENCES (self));
	g_return_if_fail (GTK_IS_CELL_RENDERER_TEXT (renderer));
	g_return_if_fail (path != NULL);
	g_return_if_fail (new_text != NULL);
	_tmp0_ = self->priv->itemstore;
	_tmp1_ = path;
	gtk_tree_model_get_iter_from_string (GTK_TREE_MODEL (_tmp0_), &_tmp2_, _tmp1_);
	iter = _tmp2_;
	_tmp3_ = self->priv->itemstore;
	_tmp4_ = iter;
	_tmp5_ = new_text;
	gtk_list_store_set (_tmp3_, &_tmp4_, 0, _tmp5_, -1);
}


void item_preferences_on_itemselection_changed (ItemPreferences* self) {
	g_return_if_fail (IS_ITEM_PREFERENCES (self));
	item_preferences_updatebuttons (self);
}


void item_preferences_on_itemsettings_changed (ItemPreferences* self) {
	gboolean _tmp0_;
	g_return_if_fail (IS_ITEM_PREFERENCES (self));
	_tmp0_ = self->priv->itemsignoresignals;
	if (!_tmp0_) {
		item_preferences_itemsgsettingstostore (self);
	}
}


void item_preferences_on_itemstore_row_inserted (GtkTreeModel* model, const gchar* path, GtkTreeIter* iter, ItemPreferences* self) {
	gboolean _tmp0_;
	g_return_if_fail (IS_ITEM_PREFERENCES (self));
	g_return_if_fail (GTK_IS_TREE_MODEL (model));
	g_return_if_fail (path != NULL);
	g_return_if_fail (iter != NULL);
	_tmp0_ = self->priv->itemsignoresignals;
	if (!_tmp0_) {
		item_preferences_itemsstoretogsettings (self);
	}
}


void item_preferences_on_itemstore_row_changed (GtkTreeModel* model, const gchar* path, GtkTreeIter* iter, ItemPreferences* self) {
	gboolean _tmp0_;
	g_return_if_fail (IS_ITEM_PREFERENCES (self));
	g_return_if_fail (GTK_IS_TREE_MODEL (model));
	g_return_if_fail (path != NULL);
	g_return_if_fail (iter != NULL);
	_tmp0_ = self->priv->itemsignoresignals;
	if (!_tmp0_) {
		item_preferences_itemsstoretogsettings (self);
	}
}


void item_preferences_on_itemstore_row_deleted (GtkTreeModel* model, const gchar* path, ItemPreferences* self) {
	gboolean _tmp0_;
	g_return_if_fail (IS_ITEM_PREFERENCES (self));
	g_return_if_fail (GTK_IS_TREE_MODEL (model));
	g_return_if_fail (path != NULL);
	_tmp0_ = self->priv->itemsignoresignals;
	if (!_tmp0_) {
		item_preferences_itemsstoretogsettings (self);
	}
}


void item_preferences_on_itemadd_clicked (GtkButton* button, ItemPreferences* self) {
	guint pos;
	GtkTreeIter iter = {0};
	GtkTreeSelection* _tmp0_;
	GtkTreeIter _tmp1_ = {0};
	gboolean _tmp2_ = FALSE;
	GtkListStore* _tmp11_;
	guint _tmp12_;
	GtkTreeIter _tmp13_ = {0};
	GtkTreeView* _tmp14_;
	GtkTreeView* _tmp15_;
	GtkListStore* _tmp16_;
	GtkTreeIter _tmp17_;
	GtkTreePath* _tmp18_ = NULL;
	GtkTreePath* _tmp19_;
	GtkTreeView* _tmp20_;
	GtkTreeViewColumn* _tmp21_ = NULL;
	g_return_if_fail (IS_ITEM_PREFERENCES (self));
	g_return_if_fail (GTK_IS_BUTTON (button));
	pos = (guint) 0;
	_tmp0_ = self->priv->itemselection;
	_tmp2_ = gtk_tree_selection_get_selected (_tmp0_, NULL, &_tmp1_);
	iter = _tmp1_;
	if (_tmp2_) {
		GtkListStore* _tmp3_;
		GtkTreeIter _tmp4_;
		GtkTreePath* _tmp5_ = NULL;
		GtkTreePath* path;
		GtkTreePath* _tmp6_;
		gint _tmp7_ = 0;
		gint* _tmp8_ = NULL;
		gint* indices;
		gint indices_length1;
		gint _indices_size_;
		gint* _tmp9_;
		gint _tmp9__length1;
		gint _tmp10_;
		_tmp3_ = self->priv->itemstore;
		_tmp4_ = iter;
		_tmp5_ = gtk_tree_model_get_path (GTK_TREE_MODEL (_tmp3_), &_tmp4_);
		path = _tmp5_;
		_tmp6_ = path;
		_tmp8_ = gtk_tree_path_get_indices_with_depth (_tmp6_, &_tmp7_);
		indices = _tmp8_;
		indices_length1 = _tmp7_;
		_indices_size_ = indices_length1;
		_tmp9_ = indices;
		_tmp9__length1 = indices_length1;
		_tmp10_ = _tmp9_[0];
		pos = (guint) (_tmp10_ + 1);
		_gtk_tree_path_free0 (path);
	}
	_tmp11_ = self->priv->itemstore;
	_tmp12_ = pos;
	gtk_list_store_insert (_tmp11_, &_tmp13_, (gint) _tmp12_);
	iter = _tmp13_;
	_tmp14_ = self->priv->itemview;
	gtk_widget_grab_focus (GTK_WIDGET (_tmp14_));
	_tmp15_ = self->priv->itemview;
	_tmp16_ = self->priv->itemstore;
	_tmp17_ = iter;
	_tmp18_ = gtk_tree_model_get_path (GTK_TREE_MODEL (_tmp16_), &_tmp17_);
	_tmp19_ = _tmp18_;
	_tmp20_ = self->priv->itemview;
	_tmp21_ = gtk_tree_view_get_column (_tmp20_, 0);
	gtk_tree_view_set_cursor (_tmp15_, _tmp19_, _tmp21_, TRUE);
	_gtk_tree_path_free0 (_tmp19_);
}


void item_preferences_on_itemremove_clicked (GtkButton* button, ItemPreferences* self) {
	GtkTreeIter iter = {0};
	GtkTreeSelection* _tmp0_;
	GtkTreeIter _tmp1_ = {0};
	gboolean _tmp2_ = FALSE;
	GtkListStore* _tmp3_;
	GtkTreeIter _tmp4_;
	GtkTreePath* _tmp5_ = NULL;
	GtkTreePath* path;
	GtkListStore* _tmp6_;
	GtkTreeIter _tmp7_;
	GtkListStore* _tmp8_;
	GtkTreePath* _tmp9_;
	GtkTreeIter _tmp10_ = {0};
	gboolean _tmp11_ = FALSE;
	GtkTreeSelection* _tmp13_;
	GtkTreePath* _tmp14_;
	g_return_if_fail (IS_ITEM_PREFERENCES (self));
	g_return_if_fail (GTK_IS_BUTTON (button));
	_tmp0_ = self->priv->itemselection;
	_tmp2_ = gtk_tree_selection_get_selected (_tmp0_, NULL, &_tmp1_);
	iter = _tmp1_;
	if (!_tmp2_) {
		return;
	}
	_tmp3_ = self->priv->itemstore;
	_tmp4_ = iter;
	_tmp5_ = gtk_tree_model_get_path (GTK_TREE_MODEL (_tmp3_), &_tmp4_);
	path = _tmp5_;
	_tmp6_ = self->priv->itemstore;
	_tmp7_ = iter;
	gtk_list_store_remove (_tmp6_, &_tmp7_);
	_tmp8_ = self->priv->itemstore;
	_tmp9_ = path;
	_tmp11_ = gtk_tree_model_get_iter (GTK_TREE_MODEL (_tmp8_), &_tmp10_, _tmp9_);
	iter = _tmp10_;
	if (!_tmp11_) {
		GtkTreePath* _tmp12_;
		_tmp12_ = path;
		gtk_tree_path_prev (_tmp12_);
	}
	_tmp13_ = self->priv->itemselection;
	_tmp14_ = path;
	gtk_tree_selection_select_path (_tmp13_, _tmp14_);
	_gtk_tree_path_free0 (path);
}


void item_preferences_on_itemedit_clicked (GtkButton* button, ItemPreferences* self) {
	GtkTreeIter iter = {0};
	GtkTreeSelection* _tmp0_;
	GtkTreeIter _tmp1_ = {0};
	gboolean _tmp2_ = FALSE;
	GtkTreeView* _tmp3_;
	GtkTreeView* _tmp4_;
	GtkListStore* _tmp5_;
	GtkTreeIter _tmp6_;
	GtkTreePath* _tmp7_ = NULL;
	GtkTreePath* _tmp8_;
	GtkTreeView* _tmp9_;
	GtkTreeViewColumn* _tmp10_ = NULL;
	g_return_if_fail (IS_ITEM_PREFERENCES (self));
	g_return_if_fail (GTK_IS_BUTTON (button));
	_tmp0_ = self->priv->itemselection;
	_tmp2_ = gtk_tree_selection_get_selected (_tmp0_, NULL, &_tmp1_);
	iter = _tmp1_;
	if (!_tmp2_) {
		return;
	}
	_tmp3_ = self->priv->itemview;
	gtk_widget_grab_focus (GTK_WIDGET (_tmp3_));
	_tmp4_ = self->priv->itemview;
	_tmp5_ = self->priv->itemstore;
	_tmp6_ = iter;
	_tmp7_ = gtk_tree_model_get_path (GTK_TREE_MODEL (_tmp5_), &_tmp6_);
	_tmp8_ = _tmp7_;
	_tmp9_ = self->priv->itemview;
	_tmp10_ = gtk_tree_view_get_column (_tmp9_, 0);
	gtk_tree_view_set_cursor (_tmp4_, _tmp8_, _tmp10_, TRUE);
	_gtk_tree_path_free0 (_tmp8_);
}


void item_preferences_on_itemup_clicked (GtkButton* button, ItemPreferences* self) {
	GtkTreeIter iter = {0};
	GtkTreeSelection* _tmp0_;
	GtkTreeIter _tmp1_ = {0};
	gboolean _tmp2_ = FALSE;
	GtkTreeIter previter = {0};
	GtkListStore* _tmp3_;
	GtkTreeIter _tmp4_;
	GtkTreePath* _tmp5_ = NULL;
	GtkTreePath* prevpath;
	GtkTreePath* _tmp6_;
	gboolean _tmp7_ = FALSE;
	GtkListStore* _tmp8_;
	GtkTreePath* _tmp9_;
	GtkTreeIter _tmp10_ = {0};
	gboolean _tmp11_ = FALSE;
	GValue value = {0};
	GValue prevvalue = {0};
	GtkListStore* _tmp12_;
	GtkTreeIter _tmp13_;
	GValue _tmp14_ = {0};
	GtkListStore* _tmp15_;
	GtkTreeIter _tmp16_;
	GValue _tmp17_ = {0};
	GtkListStore* _tmp18_;
	GtkTreeIter _tmp19_;
	GValue _tmp20_;
	GtkListStore* _tmp21_;
	GtkTreeIter _tmp22_;
	GValue _tmp23_;
	GtkTreeSelection* _tmp24_;
	GtkTreePath* _tmp25_;
	g_return_if_fail (IS_ITEM_PREFERENCES (self));
	g_return_if_fail (GTK_IS_BUTTON (button));
	_tmp0_ = self->priv->itemselection;
	_tmp2_ = gtk_tree_selection_get_selected (_tmp0_, NULL, &_tmp1_);
	iter = _tmp1_;
	if (!_tmp2_) {
		return;
	}
	_tmp3_ = self->priv->itemstore;
	_tmp4_ = iter;
	_tmp5_ = gtk_tree_model_get_path (GTK_TREE_MODEL (_tmp3_), &_tmp4_);
	prevpath = _tmp5_;
	_tmp6_ = prevpath;
	_tmp7_ = gtk_tree_path_prev (_tmp6_);
	if (!_tmp7_) {
		_gtk_tree_path_free0 (prevpath);
		return;
	}
	_tmp8_ = self->priv->itemstore;
	_tmp9_ = prevpath;
	_tmp11_ = gtk_tree_model_get_iter (GTK_TREE_MODEL (_tmp8_), &_tmp10_, _tmp9_);
	previter = _tmp10_;
	if (!_tmp11_) {
		_gtk_tree_path_free0 (prevpath);
		return;
	}
	_tmp12_ = self->priv->itemstore;
	_tmp13_ = iter;
	gtk_tree_model_get_value (GTK_TREE_MODEL (_tmp12_), &_tmp13_, 0, &_tmp14_);
	G_IS_VALUE (&value) ? (g_value_unset (&value), NULL) : NULL;
	value = _tmp14_;
	_tmp15_ = self->priv->itemstore;
	_tmp16_ = previter;
	gtk_tree_model_get_value (GTK_TREE_MODEL (_tmp15_), &_tmp16_, 0, &_tmp17_);
	G_IS_VALUE (&prevvalue) ? (g_value_unset (&prevvalue), NULL) : NULL;
	prevvalue = _tmp17_;
	_tmp18_ = self->priv->itemstore;
	_tmp19_ = iter;
	_tmp20_ = prevvalue;
	gtk_list_store_set_value (_tmp18_, &_tmp19_, 0, &_tmp20_);
	_tmp21_ = self->priv->itemstore;
	_tmp22_ = previter;
	_tmp23_ = value;
	gtk_list_store_set_value (_tmp21_, &_tmp22_, 0, &_tmp23_);
	_tmp24_ = self->priv->itemselection;
	_tmp25_ = prevpath;
	gtk_tree_selection_select_path (_tmp24_, _tmp25_);
	G_IS_VALUE (&prevvalue) ? (g_value_unset (&prevvalue), NULL) : NULL;
	G_IS_VALUE (&value) ? (g_value_unset (&value), NULL) : NULL;
	_gtk_tree_path_free0 (prevpath);
}


void item_preferences_on_itemdown_clicked (GtkButton* button, ItemPreferences* self) {
	GtkTreeIter iter = {0};
	GtkTreeSelection* _tmp0_;
	GtkTreeIter _tmp1_ = {0};
	gboolean _tmp2_ = FALSE;
	GtkTreeIter nextiter = {0};
	GtkListStore* _tmp3_;
	GtkTreeIter _tmp4_;
	GtkTreePath* _tmp5_ = NULL;
	GtkTreePath* nextpath;
	GtkTreePath* _tmp6_;
	GtkListStore* _tmp7_;
	GtkTreePath* _tmp8_;
	GtkTreeIter _tmp9_ = {0};
	gboolean _tmp10_ = FALSE;
	GValue value = {0};
	GValue nextvalue = {0};
	GtkListStore* _tmp11_;
	GtkTreeIter _tmp12_;
	GValue _tmp13_ = {0};
	GtkListStore* _tmp14_;
	GtkTreeIter _tmp15_;
	GValue _tmp16_ = {0};
	GtkListStore* _tmp17_;
	GtkTreeIter _tmp18_;
	GValue _tmp19_;
	GtkListStore* _tmp20_;
	GtkTreeIter _tmp21_;
	GValue _tmp22_;
	GtkTreeSelection* _tmp23_;
	GtkTreePath* _tmp24_;
	g_return_if_fail (IS_ITEM_PREFERENCES (self));
	g_return_if_fail (GTK_IS_BUTTON (button));
	_tmp0_ = self->priv->itemselection;
	_tmp2_ = gtk_tree_selection_get_selected (_tmp0_, NULL, &_tmp1_);
	iter = _tmp1_;
	if (!_tmp2_) {
		return;
	}
	_tmp3_ = self->priv->itemstore;
	_tmp4_ = iter;
	_tmp5_ = gtk_tree_model_get_path (GTK_TREE_MODEL (_tmp3_), &_tmp4_);
	nextpath = _tmp5_;
	_tmp6_ = nextpath;
	gtk_tree_path_next (_tmp6_);
	_tmp7_ = self->priv->itemstore;
	_tmp8_ = nextpath;
	_tmp10_ = gtk_tree_model_get_iter (GTK_TREE_MODEL (_tmp7_), &_tmp9_, _tmp8_);
	nextiter = _tmp9_;
	if (!_tmp10_) {
		_gtk_tree_path_free0 (nextpath);
		return;
	}
	_tmp11_ = self->priv->itemstore;
	_tmp12_ = iter;
	gtk_tree_model_get_value (GTK_TREE_MODEL (_tmp11_), &_tmp12_, 0, &_tmp13_);
	G_IS_VALUE (&value) ? (g_value_unset (&value), NULL) : NULL;
	value = _tmp13_;
	_tmp14_ = self->priv->itemstore;
	_tmp15_ = nextiter;
	gtk_tree_model_get_value (GTK_TREE_MODEL (_tmp14_), &_tmp15_, 0, &_tmp16_);
	G_IS_VALUE (&nextvalue) ? (g_value_unset (&nextvalue), NULL) : NULL;
	nextvalue = _tmp16_;
	_tmp17_ = self->priv->itemstore;
	_tmp18_ = iter;
	_tmp19_ = nextvalue;
	gtk_list_store_set_value (_tmp17_, &_tmp18_, 0, &_tmp19_);
	_tmp20_ = self->priv->itemstore;
	_tmp21_ = nextiter;
	_tmp22_ = value;
	gtk_list_store_set_value (_tmp20_, &_tmp21_, 0, &_tmp22_);
	_tmp23_ = self->priv->itemselection;
	_tmp24_ = nextpath;
	gtk_tree_selection_select_path (_tmp23_, _tmp24_);
	G_IS_VALUE (&nextvalue) ? (g_value_unset (&nextvalue), NULL) : NULL;
	G_IS_VALUE (&value) ? (g_value_unset (&value), NULL) : NULL;
	_gtk_tree_path_free0 (nextpath);
}


static void item_preferences_updatebuttons (ItemPreferences* self) {
	GtkTreeIter iter = {0};
	gboolean add;
	gboolean remove;
	gboolean edit;
	gboolean up;
	gboolean down;
	GtkTreeSelection* _tmp0_;
	GtkTreeIter _tmp1_ = {0};
	gboolean _tmp2_ = FALSE;
	GtkButton* _tmp15_;
	gboolean _tmp16_;
	GtkButton* _tmp17_;
	gboolean _tmp18_;
	GtkButton* _tmp19_;
	gboolean _tmp20_;
	GtkButton* _tmp21_;
	gboolean _tmp22_;
	GtkButton* _tmp23_;
	gboolean _tmp24_;
	g_return_if_fail (IS_ITEM_PREFERENCES (self));
	add = TRUE;
	remove = FALSE;
	edit = FALSE;
	up = FALSE;
	down = FALSE;
	_tmp0_ = self->priv->itemselection;
	_tmp2_ = gtk_tree_selection_get_selected (_tmp0_, NULL, &_tmp1_);
	iter = _tmp1_;
	if (_tmp2_) {
		GtkListStore* _tmp3_;
		GtkTreeIter _tmp4_;
		GtkTreePath* _tmp5_ = NULL;
		GtkTreePath* path;
		GtkTreePath* _tmp6_;
		gint _tmp7_ = 0;
		gint* _tmp8_ = NULL;
		gint* indices;
		gint indices_length1;
		gint _indices_size_;
		gint* _tmp9_;
		gint _tmp9__length1;
		gint _tmp10_;
		gint* _tmp11_;
		gint _tmp11__length1;
		gint _tmp12_;
		GtkListStore* _tmp13_;
		gint _tmp14_ = 0;
		edit = TRUE;
		remove = TRUE;
		_tmp3_ = self->priv->itemstore;
		_tmp4_ = iter;
		_tmp5_ = gtk_tree_model_get_path (GTK_TREE_MODEL (_tmp3_), &_tmp4_);
		path = _tmp5_;
		_tmp6_ = path;
		_tmp8_ = gtk_tree_path_get_indices_with_depth (_tmp6_, &_tmp7_);
		indices = _tmp8_;
		indices_length1 = _tmp7_;
		_indices_size_ = indices_length1;
		_tmp9_ = indices;
		_tmp9__length1 = indices_length1;
		_tmp10_ = _tmp9_[0];
		up = _tmp10_ > 0;
		_tmp11_ = indices;
		_tmp11__length1 = indices_length1;
		_tmp12_ = _tmp11_[0];
		_tmp13_ = self->priv->itemstore;
		_tmp14_ = gtk_tree_model_iter_n_children (GTK_TREE_MODEL (_tmp13_), NULL);
		down = (_tmp12_ + 1) < _tmp14_;
		_gtk_tree_path_free0 (path);
	}
	_tmp15_ = self->priv->itemadd;
	_tmp16_ = add;
	gtk_widget_set_sensitive (GTK_WIDGET (_tmp15_), _tmp16_);
	_tmp17_ = self->priv->itemremove;
	_tmp18_ = remove;
	gtk_widget_set_sensitive (GTK_WIDGET (_tmp17_), _tmp18_);
	_tmp19_ = self->priv->itemedit;
	_tmp20_ = edit;
	gtk_widget_set_sensitive (GTK_WIDGET (_tmp19_), _tmp20_);
	_tmp21_ = self->priv->itemup;
	_tmp22_ = up;
	gtk_widget_set_sensitive (GTK_WIDGET (_tmp21_), _tmp22_);
	_tmp23_ = self->priv->itemdown;
	_tmp24_ = down;
	gtk_widget_set_sensitive (GTK_WIDGET (_tmp23_), _tmp24_);
}


static void item_preferences_itemsgsettingstostore (ItemPreferences* self) {
	GSettings* _tmp0_;
	const gchar* _tmp1_;
	gchar** _tmp2_;
	gchar** _tmp3_ = NULL;
	gchar** expressions;
	gint expressions_length1;
	gint _expressions_size_;
	GtkListStore* _tmp4_;
	g_return_if_fail (IS_ITEM_PREFERENCES (self));
	_tmp0_ = self->priv->itemsettings;
	_tmp1_ = self->priv->_settingskey;
	_tmp3_ = _tmp2_ = g_settings_get_strv (_tmp0_, _tmp1_);
	expressions = _tmp3_;
	expressions_length1 = _vala_array_length (_tmp2_);
	_expressions_size_ = expressions_length1;
	self->priv->itemsignoresignals = TRUE;
	_tmp4_ = self->priv->itemstore;
	gtk_list_store_clear (_tmp4_);
	{
		guint i;
		gchar** _tmp5_;
		gint _tmp5__length1;
		guint isize;
		i = (guint) 0;
		_tmp5_ = expressions;
		_tmp5__length1 = expressions_length1;
		isize = (guint) _tmp5__length1;
		{
			gboolean _tmp6_;
			_tmp6_ = TRUE;
			while (TRUE) {
				gboolean _tmp7_;
				guint _tmp9_;
				guint _tmp10_;
				GtkListStore* _tmp11_;
				guint _tmp12_;
				gchar** _tmp13_;
				gint _tmp13__length1;
				guint _tmp14_;
				const gchar* _tmp15_;
				_tmp7_ = _tmp6_;
				if (!_tmp7_) {
					guint _tmp8_;
					_tmp8_ = i;
					i = _tmp8_ + 1;
				}
				_tmp6_ = FALSE;
				_tmp9_ = i;
				_tmp10_ = isize;
				if (!(_tmp9_ < _tmp10_)) {
					break;
				}
				_tmp11_ = self->priv->itemstore;
				_tmp12_ = i;
				_tmp13_ = expressions;
				_tmp13__length1 = expressions_length1;
				_tmp14_ = i;
				_tmp15_ = _tmp13_[_tmp14_];
				gtk_list_store_insert_with_values (_tmp11_, NULL, (gint) _tmp12_, 0, _tmp15_, -1);
			}
		}
	}
	self->priv->itemsignoresignals = FALSE;
	expressions = (_vala_array_free (expressions, expressions_length1, (GDestroyNotify) g_free), NULL);
}


static void item_preferences_itemsstoretogsettings (ItemPreferences* self) {
	GtkListStore* _tmp0_;
	gint _tmp1_ = 0;
	gchar** _tmp2_ = NULL;
	gchar** _result_;
	gint _result__length1;
	gint __result__size_;
	GtkTreeIter iter = {0};
	GSettings* _tmp20_;
	const gchar* _tmp21_;
	gchar** _tmp22_;
	gint _tmp22__length1;
	g_return_if_fail (IS_ITEM_PREFERENCES (self));
	_tmp0_ = self->priv->itemstore;
	_tmp1_ = gtk_tree_model_iter_n_children (GTK_TREE_MODEL (_tmp0_), NULL);
	_tmp2_ = g_new0 (gchar*, _tmp1_ + 1);
	_result_ = _tmp2_;
	_result__length1 = _tmp1_;
	__result__size_ = _result__length1;
	{
		guint i;
		gchar** _tmp3_;
		gint _tmp3__length1;
		guint isize;
		i = (guint) 0;
		_tmp3_ = _result_;
		_tmp3__length1 = _result__length1;
		isize = (guint) _tmp3__length1;
		{
			gboolean _tmp4_;
			_tmp4_ = TRUE;
			while (TRUE) {
				gboolean _tmp5_;
				guint _tmp7_;
				guint _tmp8_;
				GtkListStore* _tmp9_;
				guint _tmp10_;
				GtkTreeIter _tmp11_ = {0};
				GValue value = {0};
				GtkListStore* _tmp12_;
				GtkTreeIter _tmp13_;
				GValue _tmp14_ = {0};
				gchar** _tmp15_;
				gint _tmp15__length1;
				guint _tmp16_;
				GValue _tmp17_;
				gchar* _tmp18_;
				gchar* _tmp19_;
				_tmp5_ = _tmp4_;
				if (!_tmp5_) {
					guint _tmp6_;
					_tmp6_ = i;
					i = _tmp6_ + 1;
				}
				_tmp4_ = FALSE;
				_tmp7_ = i;
				_tmp8_ = isize;
				if (!(_tmp7_ < _tmp8_)) {
					break;
				}
				_tmp9_ = self->priv->itemstore;
				_tmp10_ = i;
				gtk_tree_model_iter_nth_child (GTK_TREE_MODEL (_tmp9_), &_tmp11_, NULL, (gint) _tmp10_);
				iter = _tmp11_;
				_tmp12_ = self->priv->itemstore;
				_tmp13_ = iter;
				gtk_tree_model_get_value (GTK_TREE_MODEL (_tmp12_), &_tmp13_, 0, &_tmp14_);
				G_IS_VALUE (&value) ? (g_value_unset (&value), NULL) : NULL;
				value = _tmp14_;
				_tmp15_ = _result_;
				_tmp15__length1 = _result__length1;
				_tmp16_ = i;
				_tmp17_ = value;
				_tmp18_ = g_strdup (g_value_get_string (&_tmp17_));
				_g_free0 (_tmp15_[_tmp16_]);
				_tmp15_[_tmp16_] = _tmp18_;
				_tmp19_ = _tmp15_[_tmp16_];
				G_IS_VALUE (&value) ? (g_value_unset (&value), NULL) : NULL;
			}
		}
	}
	self->priv->itemsignoresignals = TRUE;
	_tmp20_ = self->priv->itemsettings;
	_tmp21_ = self->priv->_settingskey;
	_tmp22_ = _result_;
	_tmp22__length1 = _result__length1;
	g_settings_set_strv (_tmp20_, _tmp21_, _tmp22_);
	self->priv->itemsignoresignals = FALSE;
	_result_ = (_vala_array_free (_result_, _result__length1, (GDestroyNotify) g_free), NULL);
}


const gchar* item_preferences_get_settingskey (ItemPreferences* self) {
	const gchar* result;
	const gchar* _tmp0_;
	g_return_val_if_fail (IS_ITEM_PREFERENCES (self), NULL);
	_tmp0_ = self->priv->_settingskey;
	result = _tmp0_;
	return result;
}


static void item_preferences_set_settingskey (ItemPreferences* self, const gchar* value) {
	const gchar* _tmp0_;
	gchar* _tmp1_;
	g_return_if_fail (IS_ITEM_PREFERENCES (self));
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_settingskey);
	self->priv->_settingskey = _tmp1_;
	g_object_notify ((GObject *) self, "settingskey");
}


static void item_preferences_class_init (ItemPreferencesClass * klass) {
	item_preferences_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (ItemPreferencesPrivate));
	G_OBJECT_CLASS (klass)->get_property = _vala_item_preferences_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_item_preferences_set_property;
	G_OBJECT_CLASS (klass)->finalize = item_preferences_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), ITEM_PREFERENCES_SETTINGSKEY, g_param_spec_string ("settingskey", "settingskey", "settingskey", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE | G_PARAM_CONSTRUCT_ONLY));
}


static void item_preferences_instance_init (ItemPreferences * self) {
	self->priv = ITEM_PREFERENCES_GET_PRIVATE (self);
}


static void item_preferences_finalize (GObject* obj) {
	ItemPreferences * self;
	self = ITEM_PREFERENCES (obj);
	_g_object_unref0 (self->priv->items);
	_g_object_unref0 (self->priv->itemstore);
	_g_object_unref0 (self->priv->itemview);
	_g_object_unref0 (self->priv->itemselection);
	_g_object_unref0 (self->priv->itemadd);
	_g_object_unref0 (self->priv->itemremove);
	_g_object_unref0 (self->priv->itemedit);
	_g_object_unref0 (self->priv->itemup);
	_g_object_unref0 (self->priv->itemdown);
	_g_object_unref0 (self->priv->itemsettings);
	_g_free0 (self->priv->_settingskey);
	G_OBJECT_CLASS (item_preferences_parent_class)->finalize (obj);
}


/******************************************************************************
 * Copyright (C) 2011  Michael Hofmann <mh21@piware.de>                       *
 *                                                                            *
 * This program is free software; you can redistribute it and/or modify       *
 * it under the terms of the GNU General Public License as published by       *
 * the Free Software Foundation; either version 3 of the License, or          *
 * (at your option) any later version.                                        *
 *                                                                            *
 * This program is distributed in the hope that it will be useful,            *
 * but WITHOUT ANY WARRANTY; without even the implied warranty of             *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the              *
 * GNU General Public License for more details.                               *
 *                                                                            *
 * You should have received a copy of the GNU General Public License along    *
 * with this program; if not, write to the Free Software Foundation, Inc.,    *
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.                *
 ******************************************************************************/
GType item_preferences_get_type (void) {
	static volatile gsize item_preferences_type_id__volatile = 0;
	if (g_once_init_enter (&item_preferences_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (ItemPreferencesClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) item_preferences_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ItemPreferences), 0, (GInstanceInitFunc) item_preferences_instance_init, NULL };
		GType item_preferences_type_id;
		item_preferences_type_id = g_type_register_static (G_TYPE_OBJECT, "ItemPreferences", &g_define_type_info, 0);
		g_once_init_leave (&item_preferences_type_id__volatile, item_preferences_type_id);
	}
	return item_preferences_type_id__volatile;
}


static void _vala_item_preferences_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	ItemPreferences * self;
	self = ITEM_PREFERENCES (object);
	switch (property_id) {
		case ITEM_PREFERENCES_SETTINGSKEY:
		g_value_set_string (value, item_preferences_get_settingskey (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_item_preferences_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	ItemPreferences * self;
	self = ITEM_PREFERENCES (object);
	switch (property_id) {
		case ITEM_PREFERENCES_SETTINGSKEY:
		item_preferences_set_settingskey (self, g_value_get_string (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}


static gint _vala_array_length (gpointer array) {
	int length;
	length = 0;
	if (array) {
		while (((gpointer*) array)[length]) {
			length++;
		}
	}
	return length;
}



