/* main.c generated by valac 0.14.2, the Vala compiler
 * generated from main.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gio/gio.h>
#include <gtk/gtk.h>
#include <stdlib.h>
#include <string.h>
#include <gio/gdesktopappinfo.h>
#include <stdio.h>
#include <config.h>
#include <glib/gstdio.h>
#include <gdk/gdk.h>
#include <glib/gi18n-lib.h>
#include <float.h>
#include <math.h>


#define TYPE_MAIN (main_get_type ())
#define MAIN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_MAIN, Main))
#define MAIN_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_MAIN, MainClass))
#define IS_MAIN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_MAIN))
#define IS_MAIN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_MAIN))
#define MAIN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_MAIN, MainClass))

typedef struct _Main Main;
typedef struct _MainClass MainClass;
typedef struct _MainPrivate MainPrivate;

#define TYPE_MULTI_LOAD_INDICATOR (multi_load_indicator_get_type ())
#define MULTI_LOAD_INDICATOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_MULTI_LOAD_INDICATOR, MultiLoadIndicator))
#define MULTI_LOAD_INDICATOR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_MULTI_LOAD_INDICATOR, MultiLoadIndicatorClass))
#define IS_MULTI_LOAD_INDICATOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_MULTI_LOAD_INDICATOR))
#define IS_MULTI_LOAD_INDICATOR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_MULTI_LOAD_INDICATOR))
#define MULTI_LOAD_INDICATOR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_MULTI_LOAD_INDICATOR, MultiLoadIndicatorClass))

typedef struct _MultiLoadIndicator MultiLoadIndicator;
typedef struct _MultiLoadIndicatorClass MultiLoadIndicatorClass;

#define TYPE_PREFERENCES (preferences_get_type ())
#define PREFERENCES(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_PREFERENCES, Preferences))
#define PREFERENCES_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_PREFERENCES, PreferencesClass))
#define IS_PREFERENCES(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_PREFERENCES))
#define IS_PREFERENCES_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_PREFERENCES))
#define PREFERENCES_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_PREFERENCES, PreferencesClass))

typedef struct _Preferences Preferences;
typedef struct _PreferencesClass PreferencesClass;

#define TYPE_SETTINGS_CACHE (settings_cache_get_type ())
#define SETTINGS_CACHE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_SETTINGS_CACHE, SettingsCache))
#define SETTINGS_CACHE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_SETTINGS_CACHE, SettingsCacheClass))
#define IS_SETTINGS_CACHE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_SETTINGS_CACHE))
#define IS_SETTINGS_CACHE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_SETTINGS_CACHE))
#define SETTINGS_CACHE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_SETTINGS_CACHE, SettingsCacheClass))

typedef struct _SettingsCache SettingsCache;
typedef struct _SettingsCacheClass SettingsCacheClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))

#define TYPE_PROVIDERS (providers_get_type ())
#define PROVIDERS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_PROVIDERS, Providers))
#define PROVIDERS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_PROVIDERS, ProvidersClass))
#define IS_PROVIDERS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_PROVIDERS))
#define IS_PROVIDERS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_PROVIDERS))
#define PROVIDERS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_PROVIDERS, ProvidersClass))

typedef struct _Providers Providers;
typedef struct _ProvidersClass ProvidersClass;

#define TYPE_GRAPH_MODELS (graph_models_get_type ())
#define GRAPH_MODELS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_GRAPH_MODELS, GraphModels))
#define GRAPH_MODELS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_GRAPH_MODELS, GraphModelsClass))
#define IS_GRAPH_MODELS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_GRAPH_MODELS))
#define IS_GRAPH_MODELS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_GRAPH_MODELS))
#define GRAPH_MODELS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_GRAPH_MODELS, GraphModelsClass))

typedef struct _GraphModels GraphModels;
typedef struct _GraphModelsClass GraphModelsClass;

#define TYPE_GRAPH_MODEL (graph_model_get_type ())
#define GRAPH_MODEL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_GRAPH_MODEL, GraphModel))
#define GRAPH_MODEL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_GRAPH_MODEL, GraphModelClass))
#define IS_GRAPH_MODEL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_GRAPH_MODEL))
#define IS_GRAPH_MODEL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_GRAPH_MODEL))
#define GRAPH_MODEL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_GRAPH_MODEL, GraphModelClass))

typedef struct _GraphModel GraphModel;
typedef struct _GraphModelClass GraphModelClass;
#define _g_list_free0(var) ((var == NULL) ? NULL : (var = (g_list_free (var), NULL)))

#define TYPE_EXPRESSION_CACHE (expression_cache_get_type ())
#define EXPRESSION_CACHE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_EXPRESSION_CACHE, ExpressionCache))
#define EXPRESSION_CACHE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_EXPRESSION_CACHE, ExpressionCacheClass))
#define IS_EXPRESSION_CACHE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_EXPRESSION_CACHE))
#define IS_EXPRESSION_CACHE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_EXPRESSION_CACHE))
#define EXPRESSION_CACHE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_EXPRESSION_CACHE, ExpressionCacheClass))

typedef struct _ExpressionCache ExpressionCache;
typedef struct _ExpressionCacheClass ExpressionCacheClass;

#define TYPE_TRACE_MODEL (trace_model_get_type ())
#define TRACE_MODEL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_TRACE_MODEL, TraceModel))
#define TRACE_MODEL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_TRACE_MODEL, TraceModelClass))
#define IS_TRACE_MODEL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_TRACE_MODEL))
#define IS_TRACE_MODEL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_TRACE_MODEL))
#define TRACE_MODEL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_TRACE_MODEL, TraceModelClass))

typedef struct _TraceModel TraceModel;
typedef struct _TraceModelClass TraceModelClass;

#define TYPE_SETTINGS_CONVERSION (settings_conversion_get_type ())
#define SETTINGS_CONVERSION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_SETTINGS_CONVERSION, SettingsConversion))
#define SETTINGS_CONVERSION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_SETTINGS_CONVERSION, SettingsConversionClass))
#define IS_SETTINGS_CONVERSION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_SETTINGS_CONVERSION))
#define IS_SETTINGS_CONVERSION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_SETTINGS_CONVERSION))
#define SETTINGS_CONVERSION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_SETTINGS_CONVERSION, SettingsConversionClass))

typedef struct _SettingsConversion SettingsConversion;
typedef struct _SettingsConversionClass SettingsConversionClass;

#define TYPE_MENU_MODEL (menu_model_get_type ())
#define MENU_MODEL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_MENU_MODEL, MenuModel))
#define MENU_MODEL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_MENU_MODEL, MenuModelClass))
#define IS_MENU_MODEL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_MENU_MODEL))
#define IS_MENU_MODEL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_MENU_MODEL))
#define MENU_MODEL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_MENU_MODEL, MenuModelClass))

typedef struct _MenuModel MenuModel;
typedef struct _MenuModelClass MenuModelClass;
#define _g_option_context_free0(var) ((var == NULL) ? NULL : (var = (g_option_context_free (var), NULL)))
#define _g_option_group_free0(var) ((var == NULL) ? NULL : (var = (g_option_group_free (var), NULL)))

#define TYPE_PROVIDER (provider_get_type ())
#define PROVIDER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_PROVIDER, Provider))
#define PROVIDER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_PROVIDER, ProviderClass))
#define IS_PROVIDER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_PROVIDER))
#define IS_PROVIDER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_PROVIDER))
#define PROVIDER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_PROVIDER, ProviderClass))

typedef struct _Provider Provider;
typedef struct _ProviderClass ProviderClass;

#define TYPE_FUNCTION (function_get_type ())
#define FUNCTION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_FUNCTION, Function))
#define FUNCTION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_FUNCTION, FunctionClass))
#define IS_FUNCTION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_FUNCTION))
#define IS_FUNCTION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_FUNCTION))
#define FUNCTION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_FUNCTION, FunctionClass))

typedef struct _Function Function;
typedef struct _FunctionClass FunctionClass;

#define TYPE_REAPER (reaper_get_type ())
#define REAPER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_REAPER, Reaper))
#define REAPER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_REAPER, ReaperClass))
#define IS_REAPER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_REAPER))
#define IS_REAPER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_REAPER))
#define REAPER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_REAPER, ReaperClass))

typedef struct _Reaper Reaper;
typedef struct _ReaperClass ReaperClass;
#define _g_key_file_free0(var) ((var == NULL) ? NULL : (var = (g_key_file_free (var), NULL)))

struct _Main {
	GApplication parent_instance;
	MainPrivate * priv;
};

struct _MainClass {
	GApplicationClass parent_class;
};

struct _MainPrivate {
	MultiLoadIndicator* multi;
	GtkDialog* about;
	Preferences* preferences;
	SettingsCache* settingscache;
	gchar* autostartkey;
	gchar* desktopfilename;
	gchar* autostartfile;
	gchar* applicationfile;
	gchar* graphsetups;
};


static gpointer main_parent_class = NULL;
static gchar* main_datadirectory;
static gchar* main_datadirectory = NULL;
static gchar** main_expressionoptions;
static gint main_expressionoptions_length1;
static gchar** main_expressionoptions = NULL;
static gint main_expressionoptions_length1 = 0;
static gint _main_expressionoptions_size_ = 0;
static gboolean main_identifiersoption;
static gboolean main_identifiersoption = FALSE;
extern gchar* utils_uifile;
extern gboolean utils_enabledebugmessages;

GType main_get_type (void) G_GNUC_CONST;
GType multi_load_indicator_get_type (void) G_GNUC_CONST;
GType preferences_get_type (void) G_GNUC_CONST;
GType settings_cache_get_type (void) G_GNUC_CONST;
#define MAIN_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_MAIN, MainPrivate))
enum  {
	MAIN_DUMMY_PROPERTY,
	MAIN_AUTOSTART
};
void multi_load_indicator_destroy (MultiLoadIndicator* self);
static gboolean main_debug (const gchar* optionname, const gchar* optionvalue, Main* self, GError** error);
void main_on_sysmon_activate (GtkMenuItem* source, Main* self);
GSettings* settings_cache_generalsettings (SettingsCache* self);
void main_on_preferences_activate (GtkMenuItem* source, Main* self);
void preferences_show (Preferences* self);
void main_on_about_activate (GtkMenuItem* source, Main* self);
GObject* utils_get_ui (const gchar* objectid, GObject* signalhandlers, gchar** additional, int additional_length1, GtkBuilder** builder);
void main_on_quit_activate (GtkMenuItem* source, Main* self);
void main_on_aboutdialog_destroy (GtkWidget* source, Main* self);
Main* main_new (const gchar* app_id, GApplicationFlags flags);
Main* main_construct (GType object_type, const gchar* app_id, GApplicationFlags flags);
static void _vala_array_add11 (gchar*** array, int* length, int* size, gchar* value);
static void main_creategraphs (Main* self, GSettings* settings, const gchar* key);
GSettings* settings_cache_graphsettings (SettingsCache* self, const gchar* graphid);
GType providers_get_type (void) G_GNUC_CONST;
Providers* multi_load_indicator_get_providers (MultiLoadIndicator* self);
GraphModels* graph_models_new (gchar** graphids, int graphids_length1, Providers* providers);
GraphModels* graph_models_construct (GType object_type, gchar** graphids, int graphids_length1, Providers* providers);
GType graph_models_get_type (void) G_GNUC_CONST;
void multi_load_indicator_set_graphmodels (MultiLoadIndicator* self, GraphModels* value);
GraphModels* multi_load_indicator_get_graphmodels (MultiLoadIndicator* self);
GType graph_model_get_type (void) G_GNUC_CONST;
GraphModel** graph_models_get_graphmodels (GraphModels* self, int* result_length1);
static void main_addgraphbinds (Main* self, GraphModel* graphmodel);
GList* settings_cache_cachedsettings (SettingsCache* self);
static void _main_creategraphs_g_settings_changed (GSettings* _sender, const gchar* key, gpointer self);
const gchar* graph_model_get_id (GraphModel* self);
gboolean utils_get_settings_color (GValue* value, GVariant* variant, void* user_data);
static gboolean _utils_get_settings_color_gsettings_bind_get_mapping (GValue* value, GVariant* variant, void* user_data);
GVariant* utils_set_settings_color (GValue* value, const GVariantType* expected_type, void* user_data);
static GVariant* _utils_set_settings_color_gsettings_bind_set_mapping (GValue* value, const GVariantType* expected_type, void* user_data);
static void __lambda10_ (void);
static void ___lambda10__gdestroy_notify (void* data);
GType expression_cache_get_type (void) G_GNUC_CONST;
ExpressionCache* graph_model_get_minimum (GraphModel* self);
ExpressionCache* graph_model_get_maximum (GraphModel* self);
gchar** graph_model_get_traces (GraphModel* self, int* result_length1);
static gchar** _vala_array_dup11 (gchar** self, int length);
GType trace_model_get_type (void) G_GNUC_CONST;
TraceModel** graph_model_get_tracemodels (GraphModel* self, int* result_length1);
static TraceModel** _vala_array_dup12 (TraceModel** self, int length);
static void main_addtracebinds (Main* self, TraceModel* tracemodel, const gchar* graphid, const gchar* traceid);
GSettings* settings_cache_tracesettings (SettingsCache* self, const gchar* graphid, const gchar* traceid);
static void __lambda11_ (void);
static void ___lambda11__gdestroy_notify (void* data);
ExpressionCache* trace_model_get_expression (TraceModel* self);
static void main_real_activate (GApplication* base);
static void main_real_startup (GApplication* base);
Providers* providers_new (void);
Providers* providers_construct (GType object_type);
MultiLoadIndicator* multi_load_indicator_new (const gchar* icondirectory, Providers* providers);
MultiLoadIndicator* multi_load_indicator_construct (GType object_type, const gchar* icondirectory, Providers* providers);
SettingsCache* settings_cache_new (void);
SettingsCache* settings_cache_construct (GType object_type);
SettingsConversion* settings_conversion_new (void);
SettingsConversion* settings_conversion_construct (GType object_type);
GType settings_conversion_get_type (void) G_GNUC_CONST;
void settings_conversion_convert (SettingsConversion* self);
void multi_load_indicator_set_menu (MultiLoadIndicator* self, GtkMenu* value);
GType menu_model_get_type (void) G_GNUC_CONST;
MenuModel* multi_load_indicator_get_menumodel (MultiLoadIndicator* self);
MenuModel* multi_load_indicator_get_labelmodel (MultiLoadIndicator* self);
MenuModel* multi_load_indicator_get_descriptionmodel (MultiLoadIndicator* self);
void multi_load_indicator_updateall (MultiLoadIndicator* self);
Preferences* preferences_new (void);
Preferences* preferences_construct (GType object_type);
static gint main_real_command_line (GApplication* base, GApplicationCommandLine* command_line);
static gboolean main_real_local_command_line (GApplication* base, gchar*** arguments, gint* exit_status);
void providers_update (Providers* self);
GType provider_get_type (void) G_GNUC_CONST;
Provider** providers_get_providers (Providers* self, int* result_length1);
const gchar* provider_get_id (Provider* self);
gchar** provider_get_keys (Provider* self, int* result_length1);
static gchar** _vala_array_dup13 (gchar** self, int length);
gdouble* provider_get_values (Provider* self, int* result_length1);
static gdouble* _vala_array_dup14 (gdouble* self, int length);
GType function_get_type (void) G_GNUC_CONST;
Function** providers_get_functions (Providers* self, int* result_length1);
const gchar* function_get_id (Function* self);
gchar** function_get_parameterdescs (Function* self, int* result_length1);
ExpressionCache* expression_cache_new (Providers* providers, const gchar* expression);
ExpressionCache* expression_cache_construct (GType object_type, Providers* providers, const gchar* expression);
gchar** expression_cache_tokens (ExpressionCache* self, int* result_length1);
gchar* expression_cache_label (ExpressionCache* self);
gchar* expression_cache_guide (ExpressionCache* self);
gint main_main (gchar** args, int args_length1);
void utils_initdebug (void);
Reaper* reaper_new (gchar** args, int args_length1);
Reaper* reaper_construct (GType object_type, gchar** args, int args_length1);
GType reaper_get_type (void) G_GNUC_CONST;
gboolean main_get_autostart (Main* self);
void main_set_autostart (Main* self, gboolean value);
static void main_finalize (GObject* obj);
static void _vala_main_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_main_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);
static gint _vala_array_length (gpointer array);

static const GOptionEntry MAIN_options[4] = {{"evaluate-expression", 'e', 0, G_OPTION_ARG_STRING_ARRAY, &main_expressionoptions, "Evaluate an expression", NULL}, {"list-identifiers", 'l', 0, G_OPTION_ARG_NONE, &main_identifiersoption, "List available expression identifiers", NULL}, {"verbose", 'v', (gint) G_OPTION_FLAG_NO_ARG, G_OPTION_ARG_CALLBACK, (void*) main_debug, "Show debug messages", NULL}, {NULL}};

void main_on_sysmon_activate (GtkMenuItem* source, Main* self) {
	SettingsCache* _tmp0_;
	GSettings* _tmp1_ = NULL;
	GSettings* settings;
	GSettings* _tmp2_;
	gchar* _tmp3_ = NULL;
	gchar* sysmon;
	const gchar* _tmp4_;
	gint _tmp5_;
	gint _tmp6_;
	const gchar* _tmp13_;
	GDesktopAppInfo* _tmp14_;
	GDesktopAppInfo* info;
	GDesktopAppInfo* _tmp15_;
	GError * _inner_error_ = NULL;
	g_return_if_fail (IS_MAIN (self));
	g_return_if_fail (GTK_IS_MENU_ITEM (source));
	_tmp0_ = self->priv->settingscache;
	_tmp1_ = settings_cache_generalsettings (_tmp0_);
	settings = _tmp1_;
	_tmp2_ = settings;
	_tmp3_ = g_settings_get_string (_tmp2_, "system-monitor");
	sysmon = _tmp3_;
	_tmp4_ = sysmon;
	_tmp5_ = strlen (_tmp4_);
	_tmp6_ = _tmp5_;
	if (_tmp6_ == 0) {
		gboolean _tmp7_ = FALSE;
		const gchar* _tmp8_ = NULL;
		gboolean _tmp10_;
		_tmp8_ = g_getenv ("XDG_CURRENT_DESKTOP");
		if (g_strcmp0 (_tmp8_, "KDE") == 0) {
			_tmp7_ = TRUE;
		} else {
			const gchar* _tmp9_ = NULL;
			_tmp9_ = g_getenv ("DESKTOP_SESSION");
			_tmp7_ = g_strcmp0 (_tmp9_, "kde-plasma") == 0;
		}
		_tmp10_ = _tmp7_;
		if (_tmp10_) {
			gchar* _tmp11_;
			_tmp11_ = g_strdup ("kde4-ksysguard.desktop");
			_g_free0 (sysmon);
			sysmon = _tmp11_;
		} else {
			gchar* _tmp12_;
			_tmp12_ = g_strdup ("gnome-system-monitor.desktop");
			_g_free0 (sysmon);
			sysmon = _tmp12_;
		}
	}
	_tmp13_ = sysmon;
	_tmp14_ = g_desktop_app_info_new (_tmp13_);
	info = _tmp14_;
	_tmp15_ = info;
	if (_tmp15_ != NULL) {
		{
			GDesktopAppInfo* _tmp16_;
			_tmp16_ = info;
			g_app_info_launch (G_APP_INFO (_tmp16_), NULL, NULL, &_inner_error_);
			if (_inner_error_ != NULL) {
				goto __catch4_g_error;
			}
		}
		goto __finally4;
		__catch4_g_error:
		{
			GError* e = NULL;
			FILE* _tmp17_;
			GError* _tmp18_;
			const gchar* _tmp19_;
			e = _inner_error_;
			_inner_error_ = NULL;
			_tmp17_ = stderr;
			_tmp18_ = e;
			_tmp19_ = _tmp18_->message;
			fprintf (_tmp17_, "Could not launch system monitor: %s\n", _tmp19_);
			_g_error_free0 (e);
		}
		__finally4:
		if (_inner_error_ != NULL) {
			_g_object_unref0 (info);
			_g_free0 (sysmon);
			_g_object_unref0 (settings);
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return;
		}
	} else {
		{
			g_spawn_command_line_async ("gnome-system-monitor", &_inner_error_);
			if (_inner_error_ != NULL) {
				goto __catch5_g_error;
			}
		}
		goto __finally5;
		__catch5_g_error:
		{
			GError* e = NULL;
			FILE* _tmp20_;
			GError* _tmp21_;
			const gchar* _tmp22_;
			e = _inner_error_;
			_inner_error_ = NULL;
			_tmp20_ = stderr;
			_tmp21_ = e;
			_tmp22_ = _tmp21_->message;
			fprintf (_tmp20_, "Could not launch system monitor: %s\n", _tmp22_);
			_g_error_free0 (e);
		}
		__finally5:
		if (_inner_error_ != NULL) {
			_g_object_unref0 (info);
			_g_free0 (sysmon);
			_g_object_unref0 (settings);
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return;
		}
	}
	_g_object_unref0 (info);
	_g_free0 (sysmon);
	_g_object_unref0 (settings);
}


void main_on_preferences_activate (GtkMenuItem* source, Main* self) {
	Preferences* _tmp0_;
	g_return_if_fail (IS_MAIN (self));
	g_return_if_fail (GTK_IS_MENU_ITEM (source));
	_tmp0_ = self->priv->preferences;
	preferences_show (_tmp0_);
}


void main_on_about_activate (GtkMenuItem* source, Main* self) {
	GtkDialog* _tmp0_;
	gchar** _tmp2_ = NULL;
	gchar** _tmp3_;
	gint _tmp3__length1;
	GObject* _tmp4_ = NULL;
	GtkDialog* _tmp5_;
	GtkDialog* _tmp6_;
	g_return_if_fail (IS_MAIN (self));
	g_return_if_fail (GTK_IS_MENU_ITEM (source));
	_tmp0_ = self->priv->about;
	if (_tmp0_ != NULL) {
		GtkDialog* _tmp1_;
		_tmp1_ = self->priv->about;
		gtk_window_present (GTK_WINDOW (_tmp1_));
		return;
	}
	_tmp2_ = g_new0 (gchar*, 0 + 1);
	_tmp3_ = _tmp2_;
	_tmp3__length1 = 0;
	_tmp4_ = utils_get_ui ("aboutdialog", G_OBJECT (self), _tmp3_, 0, NULL);
	_g_object_unref0 (self->priv->about);
	self->priv->about = GTK_IS_DIALOG (_tmp4_) ? ((GtkDialog*) _tmp4_) : NULL;
	_tmp3_ = (_vala_array_free (_tmp3_, _tmp3__length1, (GDestroyNotify) g_free), NULL);
	_tmp5_ = self->priv->about;
	g_return_if_fail (_tmp5_ != NULL);
	_tmp6_ = self->priv->about;
	gtk_widget_show_all (GTK_WIDGET (_tmp6_));
}


void main_on_quit_activate (GtkMenuItem* source, Main* self) {
	g_return_if_fail (IS_MAIN (self));
	g_return_if_fail (GTK_IS_MENU_ITEM (source));
	g_application_release (G_APPLICATION (self));
}


void main_on_aboutdialog_destroy (GtkWidget* source, Main* self) {
	g_return_if_fail (IS_MAIN (self));
	g_return_if_fail (GTK_IS_WIDGET (source));
	_g_object_unref0 (self->priv->about);
	self->priv->about = NULL;
}


static void _vala_array_add11 (gchar*** array, int* length, int* size, gchar* value) {
	if ((*length) == (*size)) {
		*size = (*size) ? (2 * (*size)) : 4;
		*array = g_renew (gchar*, *array, (*size) + 1);
	}
	(*array)[(*length)++] = value;
	(*array)[*length] = NULL;
}


Main* main_construct (GType object_type, const gchar* app_id, GApplicationFlags flags) {
	Main * self = NULL;
	const gchar* _tmp0_;
	GApplicationFlags _tmp1_;
	gchar* _tmp2_;
	gchar* _tmp3_;
	const gchar* _tmp4_ = NULL;
	const gchar* _tmp5_;
	gchar* _tmp6_ = NULL;
	const gchar* _tmp7_;
	gchar* _tmp8_ = NULL;
	gchar* _tmp9_;
	gchar** _tmp10_ = NULL;
	gchar** datadirs;
	gint datadirs_length1;
	gint _datadirs_size_;
	gchar** _tmp11_;
	gchar** _tmp12_ = NULL;
	gchar** _tmp17_;
	gint _tmp17__length1;
	g_return_val_if_fail (app_id != NULL, NULL);
	_tmp0_ = app_id;
	_tmp1_ = flags;
	self = (Main*) g_object_new (object_type, "application-id", _tmp0_, "flags", _tmp1_, NULL);
	_tmp2_ = g_strdup ("X-GNOME-Autostart-enabled");
	_g_free0 (self->priv->autostartkey);
	self->priv->autostartkey = _tmp2_;
	_tmp3_ = g_strdup ("indicator-multiload.desktop");
	_g_free0 (self->priv->desktopfilename);
	self->priv->desktopfilename = _tmp3_;
	_tmp4_ = g_get_user_config_dir ();
	_tmp5_ = self->priv->desktopfilename;
	_tmp6_ = g_build_filename (_tmp4_, "autostart", _tmp5_, NULL);
	_g_free0 (self->priv->autostartfile);
	self->priv->autostartfile = _tmp6_;
	_tmp7_ = self->priv->desktopfilename;
	_tmp8_ = g_build_filename ("applications", _tmp7_, NULL);
	_g_free0 (self->priv->applicationfile);
	self->priv->applicationfile = _tmp8_;
	_tmp9_ = g_strdup (PACKAGE_DATA_DIR);
	_tmp10_ = g_new0 (gchar*, 1 + 1);
	_tmp10_[0] = _tmp9_;
	datadirs = _tmp10_;
	datadirs_length1 = 1;
	_datadirs_size_ = datadirs_length1;
	_tmp12_ = _tmp11_ = g_get_system_data_dirs ();
	{
		gchar** datadir_collection = NULL;
		gint datadir_collection_length1 = 0;
		gint _datadir_collection_size_ = 0;
		gint datadir_it = 0;
		datadir_collection = _tmp12_;
		datadir_collection_length1 = _vala_array_length (_tmp11_);
		for (datadir_it = 0; datadir_it < _vala_array_length (_tmp11_); datadir_it = datadir_it + 1) {
			gchar* _tmp13_;
			gchar* datadir = NULL;
			_tmp13_ = g_strdup (datadir_collection[datadir_it]);
			datadir = _tmp13_;
			{
				gchar** _tmp14_;
				gint _tmp14__length1;
				const gchar* _tmp15_;
				gchar* _tmp16_ = NULL;
				_tmp14_ = datadirs;
				_tmp14__length1 = datadirs_length1;
				_tmp15_ = datadir;
				_tmp16_ = g_build_filename (_tmp15_, PACKAGE_NAME, NULL);
				_vala_array_add11 (&datadirs, &datadirs_length1, &_datadirs_size_, _tmp16_);
				_g_free0 (datadir);
			}
		}
	}
	_tmp17_ = datadirs;
	_tmp17__length1 = datadirs_length1;
	{
		gchar** datadir_collection = NULL;
		gint datadir_collection_length1 = 0;
		gint _datadir_collection_size_ = 0;
		gint datadir_it = 0;
		datadir_collection = _tmp17_;
		datadir_collection_length1 = _tmp17__length1;
		for (datadir_it = 0; datadir_it < _tmp17__length1; datadir_it = datadir_it + 1) {
			gchar* _tmp18_;
			gchar* datadir = NULL;
			_tmp18_ = g_strdup (datadir_collection[datadir_it]);
			datadir = _tmp18_;
			{
				const gchar* _tmp19_;
				gchar* _tmp20_ = NULL;
				gchar* uifile;
				const gchar* _tmp21_;
				gboolean _tmp22_ = FALSE;
				const gchar* _tmp23_;
				gchar* _tmp24_;
				_tmp19_ = datadir;
				_tmp20_ = g_build_filename (_tmp19_, "preferences.ui", NULL);
				uifile = _tmp20_;
				_tmp21_ = uifile;
				_tmp22_ = g_file_test (_tmp21_, G_FILE_TEST_IS_REGULAR);
				if (!_tmp22_) {
					_g_free0 (uifile);
					_g_free0 (datadir);
					continue;
				}
				_tmp23_ = uifile;
				_tmp24_ = g_strdup (_tmp23_);
				_g_free0 (utils_uifile);
				utils_uifile = _tmp24_;
				_g_free0 (uifile);
				_g_free0 (datadir);
				break;
			}
		}
	}
	datadirs = (_vala_array_free (datadirs, datadirs_length1, (GDestroyNotify) g_free), NULL);
	return self;
}


Main* main_new (const gchar* app_id, GApplicationFlags flags) {
	return main_construct (TYPE_MAIN, app_id, flags);
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


static void _main_creategraphs_g_settings_changed (GSettings* _sender, const gchar* key, gpointer self) {
	main_creategraphs (self, _sender, key);
}


static void main_creategraphs (Main* self, GSettings* settings, const gchar* key) {
	gchar* _tmp0_;
	gchar* newgraphsetups;
	SettingsCache* _tmp1_;
	GSettings* _tmp2_ = NULL;
	GSettings* _tmp3_;
	gchar** _tmp4_;
	gchar** _tmp5_ = NULL;
	gchar** _tmp6_;
	gint _tmp6__length1;
	const gchar* _tmp22_;
	const gchar* _tmp23_;
	const gchar* _tmp24_;
	gchar* _tmp25_;
	SettingsCache* _tmp26_;
	GSettings* _tmp27_ = NULL;
	GSettings* datasettings;
	MultiLoadIndicator* _tmp28_;
	GSettings* _tmp29_;
	gchar** _tmp30_;
	gchar** _tmp31_ = NULL;
	gchar** _tmp32_;
	gint _tmp32__length1;
	MultiLoadIndicator* _tmp33_;
	Providers* _tmp34_;
	Providers* _tmp35_;
	GraphModels* _tmp36_;
	GraphModels* _tmp37_;
	MultiLoadIndicator* _tmp38_;
	GraphModels* _tmp39_;
	GraphModels* _tmp40_;
	GraphModel** _tmp41_;
	gint _tmp41__length1;
	GraphModel** _tmp42_;
	gint _tmp42__length1;
	SettingsCache* _tmp45_;
	GList* _tmp46_ = NULL;
	GSettings* _tmp48_;
	MultiLoadIndicator* _tmp49_;
	GraphModels* _tmp50_;
	GraphModels* _tmp51_;
	GraphModel** _tmp52_;
	gint _tmp52__length1;
	GraphModel** _tmp53_;
	gint _tmp53__length1;
	g_return_if_fail (IS_MAIN (self));
	g_return_if_fail ((settings == NULL) || G_IS_SETTINGS (settings));
	g_return_if_fail (key != NULL);
	_tmp0_ = g_strdup ("");
	newgraphsetups = _tmp0_;
	_tmp1_ = self->priv->settingscache;
	_tmp2_ = settings_cache_generalsettings (_tmp1_);
	_tmp3_ = _tmp2_;
	_tmp5_ = _tmp4_ = g_settings_get_strv (_tmp3_, "graphs");
	_tmp6_ = _tmp5_;
	_tmp6__length1 = _vala_array_length (_tmp4_);
	_g_object_unref0 (_tmp3_);
	{
		gchar** graphid_collection = NULL;
		gint graphid_collection_length1 = 0;
		gint _graphid_collection_size_ = 0;
		gint graphid_it = 0;
		graphid_collection = _tmp6_;
		graphid_collection_length1 = _tmp6__length1;
		for (graphid_it = 0; graphid_it < _tmp6__length1; graphid_it = graphid_it + 1) {
			gchar* _tmp7_;
			gchar* graphid = NULL;
			_tmp7_ = g_strdup (graphid_collection[graphid_it]);
			graphid = _tmp7_;
			{
				const gchar* _tmp8_;
				const gchar* _tmp9_;
				SettingsCache* _tmp10_;
				const gchar* _tmp11_;
				GSettings* _tmp12_ = NULL;
				GSettings* _tmp13_;
				gchar** _tmp14_;
				gchar** _tmp15_ = NULL;
				gchar** _tmp16_;
				gint _tmp16__length1;
				gchar* _tmp17_ = NULL;
				gchar* _tmp18_;
				gchar* _tmp19_ = NULL;
				gchar* _tmp20_;
				gchar* _tmp21_;
				_tmp8_ = newgraphsetups;
				_tmp9_ = graphid;
				_tmp10_ = self->priv->settingscache;
				_tmp11_ = graphid;
				_tmp12_ = settings_cache_graphsettings (_tmp10_, _tmp11_);
				_tmp13_ = _tmp12_;
				_tmp15_ = _tmp14_ = g_settings_get_strv (_tmp13_, "traces");
				_tmp16_ = _tmp15_;
				_tmp16__length1 = _vala_array_length (_tmp14_);
				_tmp17_ = g_strjoinv (",", _tmp16_);
				_tmp18_ = _tmp17_;
				_tmp19_ = g_strdup_printf ("%s=%s\n", _tmp9_, _tmp18_);
				_tmp20_ = _tmp19_;
				_tmp21_ = g_strconcat (_tmp8_, _tmp20_, NULL);
				_g_free0 (newgraphsetups);
				newgraphsetups = _tmp21_;
				_g_free0 (_tmp20_);
				_g_free0 (_tmp18_);
				_tmp16_ = (_vala_array_free (_tmp16_, _tmp16__length1, (GDestroyNotify) g_free), NULL);
				_g_object_unref0 (_tmp13_);
				_g_free0 (graphid);
			}
		}
		graphid_collection = (_vala_array_free (graphid_collection, graphid_collection_length1, (GDestroyNotify) g_free), NULL);
	}
	_tmp22_ = self->priv->graphsetups;
	_tmp23_ = newgraphsetups;
	if (g_strcmp0 (_tmp22_, _tmp23_) == 0) {
		_g_free0 (newgraphsetups);
		return;
	}
	_tmp24_ = newgraphsetups;
	_tmp25_ = g_strdup (_tmp24_);
	_g_free0 (self->priv->graphsetups);
	self->priv->graphsetups = _tmp25_;
	_tmp26_ = self->priv->settingscache;
	_tmp27_ = settings_cache_generalsettings (_tmp26_);
	datasettings = _tmp27_;
	_tmp28_ = self->priv->multi;
	_tmp29_ = datasettings;
	_tmp31_ = _tmp30_ = g_settings_get_strv (_tmp29_, "graphs");
	_tmp32_ = _tmp31_;
	_tmp32__length1 = _vala_array_length (_tmp30_);
	_tmp33_ = self->priv->multi;
	_tmp34_ = multi_load_indicator_get_providers (_tmp33_);
	_tmp35_ = _tmp34_;
	_tmp36_ = graph_models_new (_tmp32_, _vala_array_length (_tmp30_), _tmp35_);
	_tmp37_ = _tmp36_;
	multi_load_indicator_set_graphmodels (_tmp28_, _tmp37_);
	_g_object_unref0 (_tmp37_);
	_tmp32_ = (_vala_array_free (_tmp32_, _tmp32__length1, (GDestroyNotify) g_free), NULL);
	_tmp38_ = self->priv->multi;
	_tmp39_ = multi_load_indicator_get_graphmodels (_tmp38_);
	_tmp40_ = _tmp39_;
	_tmp41_ = graph_models_get_graphmodels (_tmp40_, &_tmp41__length1);
	_tmp42_ = _tmp41_;
	_tmp42__length1 = _tmp41__length1;
	{
		GraphModel** graphmodel_collection = NULL;
		gint graphmodel_collection_length1 = 0;
		gint _graphmodel_collection_size_ = 0;
		gint graphmodel_it = 0;
		graphmodel_collection = _tmp42_;
		graphmodel_collection_length1 = _tmp42__length1;
		for (graphmodel_it = 0; graphmodel_it < _tmp42__length1; graphmodel_it = graphmodel_it + 1) {
			GraphModel* _tmp43_;
			GraphModel* graphmodel = NULL;
			_tmp43_ = _g_object_ref0 (graphmodel_collection[graphmodel_it]);
			graphmodel = _tmp43_;
			{
				GraphModel* _tmp44_;
				_tmp44_ = graphmodel;
				main_addgraphbinds (self, _tmp44_);
				_g_object_unref0 (graphmodel);
			}
		}
	}
	_tmp45_ = self->priv->settingscache;
	_tmp46_ = settings_cache_cachedsettings (_tmp45_);
	{
		GList* cachedsetting_collection = NULL;
		GList* cachedsetting_it = NULL;
		cachedsetting_collection = _tmp46_;
		for (cachedsetting_it = cachedsetting_collection; cachedsetting_it != NULL; cachedsetting_it = cachedsetting_it->next) {
			GSettings* cachedsetting = NULL;
			cachedsetting = (GSettings*) cachedsetting_it->data;
			{
				GSettings* _tmp47_;
				_tmp47_ = cachedsetting;
				g_signal_handlers_disconnect_by_func (_tmp47_, (void*) main_creategraphs, self);
			}
		}
		_g_list_free0 (cachedsetting_collection);
	}
	_tmp48_ = datasettings;
	g_signal_connect_object (_tmp48_, "changed::graphs", (GCallback) _main_creategraphs_g_settings_changed, self, 0);
	_tmp49_ = self->priv->multi;
	_tmp50_ = multi_load_indicator_get_graphmodels (_tmp49_);
	_tmp51_ = _tmp50_;
	_tmp52_ = graph_models_get_graphmodels (_tmp51_, &_tmp52__length1);
	_tmp53_ = _tmp52_;
	_tmp53__length1 = _tmp52__length1;
	{
		GraphModel** graphmodel_collection = NULL;
		gint graphmodel_collection_length1 = 0;
		gint _graphmodel_collection_size_ = 0;
		gint graphmodel_it = 0;
		graphmodel_collection = _tmp53_;
		graphmodel_collection_length1 = _tmp53__length1;
		for (graphmodel_it = 0; graphmodel_it < _tmp53__length1; graphmodel_it = graphmodel_it + 1) {
			GraphModel* _tmp54_;
			GraphModel* graphmodel = NULL;
			_tmp54_ = _g_object_ref0 (graphmodel_collection[graphmodel_it]);
			graphmodel = _tmp54_;
			{
				SettingsCache* _tmp55_;
				GraphModel* _tmp56_;
				const gchar* _tmp57_;
				const gchar* _tmp58_;
				GSettings* _tmp59_ = NULL;
				GSettings* graphsettings;
				GSettings* _tmp60_;
				_tmp55_ = self->priv->settingscache;
				_tmp56_ = graphmodel;
				_tmp57_ = graph_model_get_id (_tmp56_);
				_tmp58_ = _tmp57_;
				_tmp59_ = settings_cache_graphsettings (_tmp55_, _tmp58_);
				graphsettings = _tmp59_;
				_tmp60_ = graphsettings;
				g_signal_connect_object (_tmp60_, "changed::traces", (GCallback) _main_creategraphs_g_settings_changed, self, 0);
				_g_object_unref0 (graphsettings);
				_g_object_unref0 (graphmodel);
			}
		}
	}
	_g_object_unref0 (datasettings);
	_g_free0 (newgraphsetups);
}


static gboolean _utils_get_settings_color_gsettings_bind_get_mapping (GValue* value, GVariant* variant, void* user_data) {
	gboolean result;
	result = utils_get_settings_color (value, variant, user_data);
	return result;
}


static GVariant* _utils_set_settings_color_gsettings_bind_set_mapping (GValue* value, const GVariantType* expected_type, void* user_data) {
	GVariant* result;
	result = utils_set_settings_color (value, expected_type, user_data);
	return result;
}


static void __lambda10_ (void) {
}


static void ___lambda10__gdestroy_notify (void* data) {
	__lambda10_ ();
}


static gchar** _vala_array_dup11 (gchar** self, int length) {
	gchar** result;
	int i;
	result = g_new0 (gchar*, length + 1);
	for (i = 0; i < length; i++) {
		gchar* _tmp0_;
		_tmp0_ = g_strdup (self[i]);
		result[i] = _tmp0_;
	}
	return result;
}


static TraceModel** _vala_array_dup12 (TraceModel** self, int length) {
	TraceModel** result;
	int i;
	result = g_new0 (TraceModel*, length + 1);
	for (i = 0; i < length; i++) {
		TraceModel* _tmp0_;
		_tmp0_ = _g_object_ref0 (self[i]);
		result[i] = _tmp0_;
	}
	return result;
}


static void main_addgraphbinds (Main* self, GraphModel* graphmodel) {
	GraphModel* _tmp0_;
	const gchar* _tmp1_;
	const gchar* _tmp2_;
	gchar* _tmp3_;
	gchar* graphid;
	SettingsCache* _tmp4_;
	const gchar* _tmp5_;
	GSettings* _tmp6_ = NULL;
	GSettings* graphsettings;
	GSettings* _tmp7_;
	GraphModel* _tmp8_;
	GSettings* _tmp9_;
	GraphModel* _tmp10_;
	ExpressionCache* _tmp11_;
	ExpressionCache* _tmp12_;
	GSettings* _tmp13_;
	GraphModel* _tmp14_;
	ExpressionCache* _tmp15_;
	ExpressionCache* _tmp16_;
	gchar* _tmp17_;
	gchar* _tmp18_;
	gchar* _tmp19_;
	gchar* _tmp20_;
	gchar** _tmp21_ = NULL;
	gchar** graphproperties;
	gint graphproperties_length1;
	gint _graphproperties_size_;
	gchar** _tmp22_;
	gint _tmp22__length1;
	GraphModel* _tmp28_;
	gchar** _tmp29_;
	gint _tmp29__length1;
	gchar** _tmp30_;
	gint _tmp30__length1;
	gchar** _tmp31_;
	gint _tmp31__length1;
	gchar** traceids;
	gint traceids_length1;
	gint _traceids_size_;
	GraphModel* _tmp32_;
	TraceModel** _tmp33_;
	gint _tmp33__length1;
	TraceModel** _tmp34_;
	gint _tmp34__length1;
	TraceModel** _tmp35_;
	gint _tmp35__length1;
	TraceModel** tracemodels;
	gint tracemodels_length1;
	gint _tracemodels_size_;
	g_return_if_fail (IS_MAIN (self));
	g_return_if_fail (IS_GRAPH_MODEL (graphmodel));
	_tmp0_ = graphmodel;
	_tmp1_ = graph_model_get_id (_tmp0_);
	_tmp2_ = _tmp1_;
	_tmp3_ = g_strdup (_tmp2_);
	graphid = _tmp3_;
	_tmp4_ = self->priv->settingscache;
	_tmp5_ = graphid;
	_tmp6_ = settings_cache_graphsettings (_tmp4_, _tmp5_);
	graphsettings = _tmp6_;
	_tmp7_ = graphsettings;
	_tmp8_ = graphmodel;
	g_settings_bind_with_mapping (_tmp7_, "background-color", _tmp8_, "background_color", G_SETTINGS_BIND_DEFAULT, _utils_get_settings_color_gsettings_bind_get_mapping, _utils_set_settings_color_gsettings_bind_set_mapping, NULL, ___lambda10__gdestroy_notify);
	_tmp9_ = graphsettings;
	_tmp10_ = graphmodel;
	_tmp11_ = graph_model_get_minimum (_tmp10_);
	_tmp12_ = _tmp11_;
	g_settings_bind (_tmp9_, "minimum", _tmp12_, "expression", G_SETTINGS_BIND_DEFAULT);
	_tmp13_ = graphsettings;
	_tmp14_ = graphmodel;
	_tmp15_ = graph_model_get_maximum (_tmp14_);
	_tmp16_ = _tmp15_;
	g_settings_bind (_tmp13_, "maximum", _tmp16_, "expression", G_SETTINGS_BIND_DEFAULT);
	_tmp17_ = g_strdup ("enabled");
	_tmp18_ = g_strdup ("smooth");
	_tmp19_ = g_strdup ("alpha");
	_tmp20_ = g_strdup ("traces");
	_tmp21_ = g_new0 (gchar*, 4 + 1);
	_tmp21_[0] = _tmp17_;
	_tmp21_[1] = _tmp18_;
	_tmp21_[2] = _tmp19_;
	_tmp21_[3] = _tmp20_;
	graphproperties = _tmp21_;
	graphproperties_length1 = 4;
	_graphproperties_size_ = graphproperties_length1;
	_tmp22_ = graphproperties;
	_tmp22__length1 = graphproperties_length1;
	{
		gchar** property_collection = NULL;
		gint property_collection_length1 = 0;
		gint _property_collection_size_ = 0;
		gint property_it = 0;
		property_collection = _tmp22_;
		property_collection_length1 = _tmp22__length1;
		for (property_it = 0; property_it < _tmp22__length1; property_it = property_it + 1) {
			gchar* _tmp23_;
			gchar* property = NULL;
			_tmp23_ = g_strdup (property_collection[property_it]);
			property = _tmp23_;
			{
				GSettings* _tmp24_;
				const gchar* _tmp25_;
				GraphModel* _tmp26_;
				const gchar* _tmp27_;
				_tmp24_ = graphsettings;
				_tmp25_ = property;
				_tmp26_ = graphmodel;
				_tmp27_ = property;
				g_settings_bind (_tmp24_, _tmp25_, _tmp26_, _tmp27_, G_SETTINGS_BIND_DEFAULT);
				_g_free0 (property);
			}
		}
	}
	_tmp28_ = graphmodel;
	_tmp29_ = graph_model_get_traces (_tmp28_, &_tmp29__length1);
	_tmp30_ = _tmp29_;
	_tmp30__length1 = _tmp29__length1;
	_tmp31_ = (_tmp30_ != NULL) ? _vala_array_dup11 (_tmp30_, _tmp30__length1) : ((gpointer) _tmp30_);
	_tmp31__length1 = _tmp30__length1;
	traceids = _tmp31_;
	traceids_length1 = _tmp31__length1;
	_traceids_size_ = traceids_length1;
	_tmp32_ = graphmodel;
	_tmp33_ = graph_model_get_tracemodels (_tmp32_, &_tmp33__length1);
	_tmp34_ = _tmp33_;
	_tmp34__length1 = _tmp33__length1;
	_tmp35_ = (_tmp34_ != NULL) ? _vala_array_dup12 (_tmp34_, _tmp34__length1) : ((gpointer) _tmp34_);
	_tmp35__length1 = _tmp34__length1;
	tracemodels = _tmp35_;
	tracemodels_length1 = _tmp35__length1;
	_tracemodels_size_ = tracemodels_length1;
	{
		guint i;
		gchar** _tmp36_;
		gint _tmp36__length1;
		guint isize;
		i = (guint) 0;
		_tmp36_ = traceids;
		_tmp36__length1 = traceids_length1;
		isize = (guint) _tmp36__length1;
		{
			gboolean _tmp37_;
			_tmp37_ = TRUE;
			while (TRUE) {
				gboolean _tmp38_;
				guint _tmp40_;
				guint _tmp41_;
				TraceModel** _tmp42_;
				gint _tmp42__length1;
				guint _tmp43_;
				TraceModel* _tmp44_;
				const gchar* _tmp45_;
				gchar** _tmp46_;
				gint _tmp46__length1;
				guint _tmp47_;
				const gchar* _tmp48_;
				_tmp38_ = _tmp37_;
				if (!_tmp38_) {
					guint _tmp39_;
					_tmp39_ = i;
					i = _tmp39_ + 1;
				}
				_tmp37_ = FALSE;
				_tmp40_ = i;
				_tmp41_ = isize;
				if (!(_tmp40_ < _tmp41_)) {
					break;
				}
				_tmp42_ = tracemodels;
				_tmp42__length1 = tracemodels_length1;
				_tmp43_ = i;
				_tmp44_ = _tmp42_[_tmp43_];
				_tmp45_ = graphid;
				_tmp46_ = traceids;
				_tmp46__length1 = traceids_length1;
				_tmp47_ = i;
				_tmp48_ = _tmp46_[_tmp47_];
				main_addtracebinds (self, _tmp44_, _tmp45_, _tmp48_);
			}
		}
	}
	tracemodels = (_vala_array_free (tracemodels, tracemodels_length1, (GDestroyNotify) g_object_unref), NULL);
	traceids = (_vala_array_free (traceids, traceids_length1, (GDestroyNotify) g_free), NULL);
	graphproperties = (_vala_array_free (graphproperties, graphproperties_length1, (GDestroyNotify) g_free), NULL);
	_g_object_unref0 (graphsettings);
	_g_free0 (graphid);
}


static void __lambda11_ (void) {
}


static void ___lambda11__gdestroy_notify (void* data) {
	__lambda11_ ();
}


static void main_addtracebinds (Main* self, TraceModel* tracemodel, const gchar* graphid, const gchar* traceid) {
	SettingsCache* _tmp0_;
	const gchar* _tmp1_;
	const gchar* _tmp2_;
	GSettings* _tmp3_ = NULL;
	GSettings* tracesettings;
	TraceModel* _tmp4_;
	TraceModel* _tmp5_;
	TraceModel* _tmp6_;
	ExpressionCache* _tmp7_;
	ExpressionCache* _tmp8_;
	g_return_if_fail (IS_MAIN (self));
	g_return_if_fail (IS_TRACE_MODEL (tracemodel));
	g_return_if_fail (graphid != NULL);
	g_return_if_fail (traceid != NULL);
	_tmp0_ = self->priv->settingscache;
	_tmp1_ = graphid;
	_tmp2_ = traceid;
	_tmp3_ = settings_cache_tracesettings (_tmp0_, _tmp1_, _tmp2_);
	tracesettings = _tmp3_;
	_tmp4_ = tracemodel;
	g_settings_bind_with_mapping (tracesettings, "color", _tmp4_, "color", G_SETTINGS_BIND_DEFAULT, _utils_get_settings_color_gsettings_bind_get_mapping, _utils_set_settings_color_gsettings_bind_set_mapping, NULL, ___lambda11__gdestroy_notify);
	_tmp5_ = tracemodel;
	g_settings_bind (tracesettings, "enabled", _tmp5_, "enabled", G_SETTINGS_BIND_DEFAULT);
	_tmp6_ = tracemodel;
	_tmp7_ = trace_model_get_expression (_tmp6_);
	_tmp8_ = _tmp7_;
	g_settings_bind (tracesettings, "expression", _tmp8_, "expression", G_SETTINGS_BIND_DEFAULT);
	_g_object_unref0 (tracesettings);
}


static gboolean main_debug (const gchar* optionname, const gchar* optionvalue, Main* self, GError** error) {
	gboolean result = FALSE;
	g_return_val_if_fail (IS_MAIN (self), FALSE);
	g_return_val_if_fail (optionname != NULL, FALSE);
	utils_enabledebugmessages = TRUE;
	result = TRUE;
	return result;
}


static void main_real_activate (GApplication* base) {
	Main * self;
	self = MAIN (base);
}


static void main_real_startup (GApplication* base) {
	Main * self;
	const gchar* _tmp0_;
	gchar* _tmp1_ = NULL;
	gchar* _tmp2_;
	Providers* _tmp3_;
	Providers* _tmp4_;
	MultiLoadIndicator* _tmp5_;
	SettingsCache* _tmp6_;
	SettingsConversion* _tmp7_;
	SettingsConversion* _tmp8_;
	gchar** _tmp9_ = NULL;
	gchar** _tmp10_;
	gint _tmp10__length1;
	GObject* _tmp11_ = NULL;
	GtkMenu* _tmp12_;
	GtkMenu* menu;
	MultiLoadIndicator* _tmp13_;
	SettingsCache* _tmp14_;
	GSettings* _tmp15_ = NULL;
	GSettings* datasettings;
	MultiLoadIndicator* _tmp16_;
	MenuModel* _tmp17_;
	MenuModel* _tmp18_;
	MultiLoadIndicator* _tmp19_;
	MenuModel* _tmp20_;
	MenuModel* _tmp21_;
	MultiLoadIndicator* _tmp22_;
	MenuModel* _tmp23_;
	MenuModel* _tmp24_;
	MultiLoadIndicator* _tmp25_;
	MultiLoadIndicator* _tmp26_;
	MultiLoadIndicator* _tmp27_;
	MultiLoadIndicator* _tmp28_;
	MultiLoadIndicator* _tmp29_;
	Preferences* _tmp30_;
	self = MAIN (base);
	_tmp0_ = main_datadirectory;
	_tmp1_ = g_build_filename (_tmp0_, "icons", NULL);
	_tmp2_ = _tmp1_;
	_tmp3_ = providers_new ();
	_tmp4_ = _tmp3_;
	_tmp5_ = multi_load_indicator_new (_tmp2_, _tmp4_);
	_g_object_unref0 (self->priv->multi);
	self->priv->multi = _tmp5_;
	_g_object_unref0 (_tmp4_);
	_g_free0 (_tmp2_);
	_tmp6_ = settings_cache_new ();
	_g_object_unref0 (self->priv->settingscache);
	self->priv->settingscache = _tmp6_;
	_tmp7_ = settings_conversion_new ();
	_tmp8_ = _tmp7_;
	settings_conversion_convert (_tmp8_);
	_g_object_unref0 (_tmp8_);
	main_creategraphs (self, NULL, "");
	_tmp9_ = g_new0 (gchar*, 0 + 1);
	_tmp10_ = _tmp9_;
	_tmp10__length1 = 0;
	_tmp11_ = utils_get_ui ("menu", G_OBJECT (self), _tmp10_, 0, NULL);
	_tmp12_ = GTK_IS_MENU (_tmp11_) ? ((GtkMenu*) _tmp11_) : NULL;
	_tmp10_ = (_vala_array_free (_tmp10_, _tmp10__length1, (GDestroyNotify) g_free), NULL);
	menu = _tmp12_;
	g_return_if_fail (menu != NULL);
	_tmp13_ = self->priv->multi;
	multi_load_indicator_set_menu (_tmp13_, menu);
	_tmp14_ = self->priv->settingscache;
	_tmp15_ = settings_cache_generalsettings (_tmp14_);
	datasettings = _tmp15_;
	_tmp16_ = self->priv->multi;
	_tmp17_ = multi_load_indicator_get_menumodel (_tmp16_);
	_tmp18_ = _tmp17_;
	g_settings_bind (datasettings, "menu-expressions", _tmp18_, "expressions", G_SETTINGS_BIND_DEFAULT);
	_tmp19_ = self->priv->multi;
	_tmp20_ = multi_load_indicator_get_labelmodel (_tmp19_);
	_tmp21_ = _tmp20_;
	g_settings_bind (datasettings, "indicator-expressions", _tmp21_, "expressions", G_SETTINGS_BIND_DEFAULT);
	_tmp22_ = self->priv->multi;
	_tmp23_ = multi_load_indicator_get_descriptionmodel (_tmp22_);
	_tmp24_ = _tmp23_;
	g_settings_bind (datasettings, "description-expressions", _tmp24_, "expressions", G_SETTINGS_BIND_DEFAULT);
	_tmp25_ = self->priv->multi;
	g_settings_bind (datasettings, "indicator-expression-index", _tmp25_, "indicator-index", G_SETTINGS_BIND_DEFAULT);
	_tmp26_ = self->priv->multi;
	g_settings_bind (datasettings, "width", _tmp26_, "width", G_SETTINGS_BIND_DEFAULT);
	_tmp27_ = self->priv->multi;
	g_settings_bind (datasettings, "height", _tmp27_, "height", G_SETTINGS_BIND_DEFAULT);
	g_settings_bind (datasettings, "autostart", self, "autostart", G_SETTINGS_BIND_DEFAULT);
	_tmp28_ = self->priv->multi;
	g_settings_bind (datasettings, "speed", _tmp28_, "speed", G_SETTINGS_BIND_DEFAULT);
	_tmp29_ = self->priv->multi;
	multi_load_indicator_updateall (_tmp29_);
	_tmp30_ = preferences_new ();
	_g_object_unref0 (self->priv->preferences);
	self->priv->preferences = _tmp30_;
	g_application_hold (G_APPLICATION (self));
	gdk_notify_startup_complete ();
	G_APPLICATION_CLASS (main_parent_class)->startup (G_APPLICATION (self));
	_g_object_unref0 (datasettings);
	_g_object_unref0 (menu);
}


static gint main_real_command_line (GApplication* base, GApplicationCommandLine* command_line) {
	Main * self;
	gint result = 0;
	self = MAIN (base);
	g_return_val_if_fail (G_IS_APPLICATION_COMMAND_LINE (command_line), 0);
	result = 0;
	return result;
}


static gchar** _vala_array_dup13 (gchar** self, int length) {
	gchar** result;
	int i;
	result = g_new0 (gchar*, length + 1);
	for (i = 0; i < length; i++) {
		gchar* _tmp0_;
		_tmp0_ = g_strdup (self[i]);
		result[i] = _tmp0_;
	}
	return result;
}


static gdouble* _vala_array_dup14 (gdouble* self, int length) {
	return g_memdup (self, length * sizeof (gdouble));
}


static gboolean main_real_local_command_line (GApplication* base, gchar*** arguments, gint* exit_status) {
	Main * self;
	gint _vala_exit_status = 0;
	gboolean result = FALSE;
	gboolean _result_;
	gboolean _tmp18_;
	gchar** _tmp64_;
	gint _tmp64__length1;
	GError * _inner_error_ = NULL;
	self = MAIN (base);
	{
		GOptionGroup* _tmp0_;
		GOptionGroup* group;
		GOptionGroup* _tmp1_;
		const gchar* _tmp2_ = NULL;
		GOptionContext* _tmp3_;
		GOptionContext* context;
		GOptionContext* _tmp4_;
		GOptionContext* _tmp5_;
		GOptionGroup* _tmp6_;
		GOptionContext* _tmp7_;
		GOptionGroup* _tmp8_ = NULL;
		gchar** _tmp9_;
		gint _tmp9__length1;
		gchar** local_args;
		gint local_args_length1;
		gint _local_args_size_;
		GOptionContext* _tmp10_;
		_tmp0_ = g_option_group_new ("", "", "", self, NULL);
		group = _tmp0_;
		_tmp1_ = group;
		g_option_group_add_entries (_tmp1_, MAIN_options);
		_tmp2_ = _ ("- System load application indicator");
		_tmp3_ = g_option_context_new (_tmp2_);
		context = _tmp3_;
		_tmp4_ = context;
		g_option_context_set_help_enabled (_tmp4_, TRUE);
		_tmp5_ = context;
		_tmp6_ = group;
		group = NULL;
		g_option_context_set_main_group (_tmp5_, _tmp6_);
		_tmp7_ = context;
		_tmp8_ = gtk_get_option_group (TRUE);
		g_option_context_add_group (_tmp7_, _tmp8_);
		_tmp9_ = *arguments;
		_tmp9__length1 = _vala_array_length (*arguments);
		local_args = _tmp9_;
		local_args_length1 = _tmp9__length1;
		_local_args_size_ = local_args_length1;
		_tmp10_ = context;
		g_option_context_parse (_tmp10_, &local_args_length1, &local_args, &_inner_error_);
		if (_inner_error_ != NULL) {
			_g_option_context_free0 (context);
			_g_option_group_free0 (group);
			if (_inner_error_->domain == G_OPTION_ERROR) {
				goto __catch6_g_option_error;
			}
			_g_option_context_free0 (context);
			_g_option_group_free0 (group);
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return FALSE;
		}
		_g_option_context_free0 (context);
		_g_option_group_free0 (group);
	}
	goto __finally6;
	__catch6_g_option_error:
	{
		GError* e = NULL;
		FILE* _tmp11_;
		GError* _tmp12_;
		const gchar* _tmp13_;
		FILE* _tmp14_;
		const gchar* _tmp15_ = NULL;
		gchar** _tmp16_;
		gint _tmp16__length1;
		const gchar* _tmp17_;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp11_ = stdout;
		_tmp12_ = e;
		_tmp13_ = _tmp12_->message;
		fprintf (_tmp11_, "%s\n", _tmp13_);
		_tmp14_ = stdout;
		_tmp15_ = _ ("Run '%s --help' to see a full list of available command line options.\n");
		_tmp16_ = *arguments;
		_tmp16__length1 = _vala_array_length (*arguments);
		_tmp17_ = _tmp16_[0];
		fprintf (_tmp14_, _tmp15_, _tmp17_);
		_vala_exit_status = 1;
		result = TRUE;
		_g_error_free0 (e);
		if (exit_status) {
			*exit_status = _vala_exit_status;
		}
		return result;
	}
	__finally6:
	if (_inner_error_ != NULL) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return FALSE;
	}
	_result_ = FALSE;
	_tmp18_ = main_identifiersoption;
	if (_tmp18_) {
		Providers* _tmp19_;
		Providers* providers;
		Providers* _tmp20_;
		Providers* _tmp21_;
		Provider** _tmp22_;
		gint _tmp22__length1;
		Provider** _tmp23_;
		gint _tmp23__length1;
		FILE* _tmp50_;
		Providers* _tmp51_;
		Function** _tmp52_;
		gint _tmp52__length1;
		Function** _tmp53_;
		gint _tmp53__length1;
		_tmp19_ = providers_new ();
		providers = _tmp19_;
		g_usleep ((gulong) 100000);
		_tmp20_ = providers;
		providers_update (_tmp20_);
		_tmp21_ = providers;
		_tmp22_ = providers_get_providers (_tmp21_, &_tmp22__length1);
		_tmp23_ = _tmp22_;
		_tmp23__length1 = _tmp22__length1;
		{
			Provider** provider_collection = NULL;
			gint provider_collection_length1 = 0;
			gint _provider_collection_size_ = 0;
			gint provider_it = 0;
			provider_collection = _tmp23_;
			provider_collection_length1 = _tmp23__length1;
			for (provider_it = 0; provider_it < _tmp23__length1; provider_it = provider_it + 1) {
				Provider* _tmp24_;
				Provider* provider = NULL;
				_tmp24_ = _g_object_ref0 (provider_collection[provider_it]);
				provider = _tmp24_;
				{
					FILE* _tmp25_;
					Provider* _tmp26_;
					const gchar* _tmp27_;
					const gchar* _tmp28_;
					Provider* _tmp29_;
					gchar** _tmp30_;
					gint _tmp30__length1;
					gchar** _tmp31_;
					gint _tmp31__length1;
					gchar** _tmp32_;
					gint _tmp32__length1;
					gchar** keys;
					gint keys_length1;
					gint _keys_size_;
					Provider* _tmp33_;
					gdouble* _tmp34_;
					gint _tmp34__length1;
					gdouble* _tmp35_;
					gint _tmp35__length1;
					gdouble* _tmp36_;
					gint _tmp36__length1;
					gdouble* values;
					gint values_length1;
					gint _values_size_;
					_tmp25_ = stdout;
					_tmp26_ = provider;
					_tmp27_ = provider_get_id (_tmp26_);
					_tmp28_ = _tmp27_;
					fprintf (_tmp25_, "%s:\n", _tmp28_);
					_tmp29_ = provider;
					_tmp30_ = provider_get_keys (_tmp29_, &_tmp30__length1);
					_tmp31_ = _tmp30_;
					_tmp31__length1 = _tmp30__length1;
					_tmp32_ = (_tmp31_ != NULL) ? _vala_array_dup13 (_tmp31_, _tmp31__length1) : ((gpointer) _tmp31_);
					_tmp32__length1 = _tmp31__length1;
					keys = _tmp32_;
					keys_length1 = _tmp32__length1;
					_keys_size_ = keys_length1;
					_tmp33_ = provider;
					_tmp34_ = provider_get_values (_tmp33_, &_tmp34__length1);
					_tmp35_ = _tmp34_;
					_tmp35__length1 = _tmp34__length1;
					_tmp36_ = (_tmp35_ != NULL) ? _vala_array_dup14 (_tmp35_, _tmp35__length1) : ((gpointer) _tmp35_);
					_tmp36__length1 = _tmp35__length1;
					values = _tmp36_;
					values_length1 = _tmp36__length1;
					_values_size_ = values_length1;
					{
						guint i;
						gchar** _tmp37_;
						gint _tmp37__length1;
						guint isize;
						i = (guint) 0;
						_tmp37_ = keys;
						_tmp37__length1 = keys_length1;
						isize = (guint) _tmp37__length1;
						{
							gboolean _tmp38_;
							_tmp38_ = TRUE;
							while (TRUE) {
								gboolean _tmp39_;
								guint _tmp41_;
								guint _tmp42_;
								FILE* _tmp43_;
								gchar** _tmp44_;
								gint _tmp44__length1;
								guint _tmp45_;
								const gchar* _tmp46_;
								gdouble* _tmp47_;
								gint _tmp47__length1;
								guint _tmp48_;
								gdouble _tmp49_;
								_tmp39_ = _tmp38_;
								if (!_tmp39_) {
									guint _tmp40_;
									_tmp40_ = i;
									i = _tmp40_ + 1;
								}
								_tmp38_ = FALSE;
								_tmp41_ = i;
								_tmp42_ = isize;
								if (!(_tmp41_ < _tmp42_)) {
									break;
								}
								_tmp43_ = stdout;
								_tmp44_ = keys;
								_tmp44__length1 = keys_length1;
								_tmp45_ = i;
								_tmp46_ = _tmp44_[_tmp45_];
								_tmp47_ = values;
								_tmp47__length1 = values_length1;
								_tmp48_ = i;
								_tmp49_ = _tmp47_[_tmp48_];
								fprintf (_tmp43_, "  %s: %f\n", _tmp46_, _tmp49_);
							}
						}
					}
					values = (g_free (values), NULL);
					keys = (_vala_array_free (keys, keys_length1, (GDestroyNotify) g_free), NULL);
					_g_object_unref0 (provider);
				}
			}
		}
		_tmp50_ = stdout;
		fprintf (_tmp50_, "functions:\n");
		_tmp51_ = providers;
		_tmp52_ = providers_get_functions (_tmp51_, &_tmp52__length1);
		_tmp53_ = _tmp52_;
		_tmp53__length1 = _tmp52__length1;
		{
			Function** function_collection = NULL;
			gint function_collection_length1 = 0;
			gint _function_collection_size_ = 0;
			gint function_it = 0;
			function_collection = _tmp53_;
			function_collection_length1 = _tmp53__length1;
			for (function_it = 0; function_it < _tmp53__length1; function_it = function_it + 1) {
				Function* _tmp54_;
				Function* function = NULL;
				_tmp54_ = _g_object_ref0 (function_collection[function_it]);
				function = _tmp54_;
				{
					FILE* _tmp55_;
					Function* _tmp56_;
					const gchar* _tmp57_;
					const gchar* _tmp58_;
					Function* _tmp59_;
					gchar** _tmp60_;
					gint _tmp60__length1;
					gchar** _tmp61_;
					gint _tmp61__length1;
					gchar* _tmp62_ = NULL;
					gchar* _tmp63_;
					_tmp55_ = stdout;
					_tmp56_ = function;
					_tmp57_ = function_get_id (_tmp56_);
					_tmp58_ = _tmp57_;
					_tmp59_ = function;
					_tmp60_ = function_get_parameterdescs (_tmp59_, &_tmp60__length1);
					_tmp61_ = _tmp60_;
					_tmp61__length1 = _tmp60__length1;
					_tmp62_ = g_strjoinv (", ", _tmp61_);
					_tmp63_ = _tmp62_;
					fprintf (_tmp55_, "  %s(%s)\n", _tmp58_, _tmp63_);
					_g_free0 (_tmp63_);
					_g_object_unref0 (function);
				}
			}
		}
		_result_ = TRUE;
		_g_object_unref0 (providers);
	}
	_tmp64_ = main_expressionoptions;
	_tmp64__length1 = _vala_array_length (main_expressionoptions);
	{
		gchar** expressionoption_collection = NULL;
		gint expressionoption_collection_length1 = 0;
		gint _expressionoption_collection_size_ = 0;
		gint expressionoption_it = 0;
		expressionoption_collection = _tmp64_;
		expressionoption_collection_length1 = _tmp64__length1;
		for (expressionoption_it = 0; expressionoption_it < _tmp64__length1; expressionoption_it = expressionoption_it + 1) {
			gchar* _tmp65_;
			gchar* expressionoption = NULL;
			_tmp65_ = g_strdup (expressionoption_collection[expressionoption_it]);
			expressionoption = _tmp65_;
			{
				Providers* _tmp66_;
				Providers* _tmp67_;
				const gchar* _tmp68_;
				ExpressionCache* _tmp69_;
				ExpressionCache* _tmp70_;
				ExpressionCache* cache;
				FILE* _tmp71_;
				const gchar* _tmp72_;
				FILE* _tmp73_;
				ExpressionCache* _tmp74_;
				gint _tmp75_ = 0;
				gchar** _tmp76_ = NULL;
				gchar** _tmp77_;
				gint _tmp77__length1;
				gchar* _tmp78_ = NULL;
				gchar* _tmp79_;
				FILE* _tmp80_;
				ExpressionCache* _tmp81_;
				gchar* _tmp82_ = NULL;
				gchar* _tmp83_;
				FILE* _tmp84_;
				ExpressionCache* _tmp85_;
				gchar* _tmp86_ = NULL;
				gchar* _tmp87_;
				_tmp66_ = providers_new ();
				_tmp67_ = _tmp66_;
				_tmp68_ = expressionoption;
				_tmp69_ = expression_cache_new (_tmp67_, _tmp68_);
				_tmp70_ = _tmp69_;
				_g_object_unref0 (_tmp67_);
				cache = _tmp70_;
				_tmp71_ = stdout;
				_tmp72_ = expressionoption;
				fprintf (_tmp71_, "Original: %s\n", _tmp72_);
				_tmp73_ = stdout;
				_tmp74_ = cache;
				_tmp76_ = expression_cache_tokens (_tmp74_, &_tmp75_);
				_tmp77_ = _tmp76_;
				_tmp77__length1 = _tmp75_;
				_tmp78_ = g_strjoinv ("' '", _tmp77_);
				_tmp79_ = _tmp78_;
				fprintf (_tmp73_, "Tokens: '%s'\n", _tmp79_);
				_g_free0 (_tmp79_);
				_tmp77_ = (_vala_array_free (_tmp77_, _tmp77__length1, (GDestroyNotify) g_free), NULL);
				_tmp80_ = stdout;
				_tmp81_ = cache;
				_tmp82_ = expression_cache_label (_tmp81_);
				_tmp83_ = _tmp82_;
				fprintf (_tmp80_, "Result: %s\n", _tmp83_);
				_g_free0 (_tmp83_);
				_tmp84_ = stdout;
				_tmp85_ = cache;
				_tmp86_ = expression_cache_guide (_tmp85_);
				_tmp87_ = _tmp86_;
				fprintf (_tmp84_, "Guide: %s\n", _tmp87_);
				_g_free0 (_tmp87_);
				_result_ = TRUE;
				_g_object_unref0 (cache);
				_g_free0 (expressionoption);
			}
		}
	}
	result = _result_;
	if (exit_status) {
		*exit_status = _vala_exit_status;
	}
	return result;
}


gint main_main (gchar** args, int args_length1) {
	gint result = 0;
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_;
	gchar* directory;
	gboolean _tmp2_ = FALSE;
	const gchar* _tmp3_;
	gboolean _tmp7_;
	const gchar* _tmp9_;
	gchar* _tmp10_;
	gchar* _tmp11_;
	const gchar* _tmp12_ = NULL;
	gchar* _tmp13_;
	const gchar* _tmp14_ = NULL;
	gchar* _tmp15_;
	gchar* xdgdatadirs;
	const gchar* _tmp16_;
	gint _tmp17_;
	gint _tmp18_;
	const gchar* _tmp21_;
	const gchar* _tmp22_;
	gchar* _tmp23_;
	gchar* _tmp24_;
	gchar** _tmp25_;
	gint _tmp25__length1;
	Reaper* _tmp26_;
	Reaper* reaper;
	Main* _tmp27_;
	Main* _tmp28_;
	gchar** _tmp29_;
	gint _tmp29__length1;
	gint _tmp30_ = 0;
	gint _tmp31_;
	gint _result_;
	const gchar* _tmp32_;
	bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
	bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
	textdomain (GETTEXT_PACKAGE);
	_tmp0_ = g_getenv ("XDG_RUNTIME_DIR");
	_tmp1_ = g_strdup (_tmp0_);
	directory = _tmp1_;
	_tmp3_ = directory;
	if (_tmp3_ == NULL) {
		_tmp2_ = TRUE;
	} else {
		const gchar* _tmp4_;
		gint _tmp5_;
		gint _tmp6_;
		_tmp4_ = directory;
		_tmp5_ = strlen (_tmp4_);
		_tmp6_ = _tmp5_;
		_tmp2_ = _tmp6_ == 0;
	}
	_tmp7_ = _tmp2_;
	if (_tmp7_) {
		gchar* _tmp8_;
		_tmp8_ = g_strdup ("/var/lock");
		_g_free0 (directory);
		directory = _tmp8_;
	}
	_tmp9_ = directory;
	_tmp10_ = g_strconcat (_tmp9_, "/multiload-icons-XXXXXX", NULL);
	_tmp11_ = _tmp10_;
	_tmp12_ = mkdtemp (_tmp11_);
	_tmp13_ = g_strdup (_tmp12_);
	_g_free0 (main_datadirectory);
	main_datadirectory = _tmp13_;
	_g_free0 (_tmp11_);
	_tmp14_ = g_getenv ("XDG_DATA_DIRS");
	_tmp15_ = g_strdup (_tmp14_);
	xdgdatadirs = _tmp15_;
	_tmp16_ = xdgdatadirs;
	_tmp17_ = strlen (_tmp16_);
	_tmp18_ = _tmp17_;
	if (_tmp18_ > 0) {
		const gchar* _tmp19_;
		gchar* _tmp20_;
		_tmp19_ = xdgdatadirs;
		_tmp20_ = g_strconcat (_tmp19_, ":", NULL);
		_g_free0 (xdgdatadirs);
		xdgdatadirs = _tmp20_;
	}
	_tmp21_ = xdgdatadirs;
	_tmp22_ = main_datadirectory;
	_tmp23_ = g_strconcat (_tmp21_, _tmp22_, NULL);
	_tmp24_ = _tmp23_;
	g_setenv ("XDG_DATA_DIRS", _tmp24_, TRUE);
	_g_free0 (_tmp24_);
	utils_initdebug ();
	gtk_init (&args_length1, &args);
	gtk_window_set_default_icon_name ("utilities-system-monitor");
	_tmp25_ = args;
	_tmp25__length1 = args_length1;
	_tmp26_ = reaper_new (_tmp25_, _tmp25__length1);
	reaper = _tmp26_;
	_tmp27_ = main_new ("de.mh21.indicator.multiload", G_APPLICATION_FLAGS_NONE);
	_tmp28_ = _tmp27_;
	_tmp29_ = args;
	_tmp29__length1 = args_length1;
	_tmp30_ = g_application_run (G_APPLICATION (_tmp28_), _tmp29__length1, _tmp29_);
	_tmp31_ = _tmp30_;
	_g_object_unref0 (_tmp28_);
	_result_ = _tmp31_;
	_tmp32_ = main_datadirectory;
	g_rmdir (_tmp32_);
	result = _result_;
	_g_object_unref0 (reaper);
	_g_free0 (xdgdatadirs);
	_g_free0 (directory);
	return result;
}


int main (int argc, char ** argv) {
	g_type_init ();
	return main_main (argv, argc);
}


gboolean main_get_autostart (Main* self) {
	gboolean result;
	GKeyFile* _tmp0_;
	GKeyFile* file;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (IS_MAIN (self), FALSE);
	_tmp0_ = g_key_file_new ();
	file = _tmp0_;
	{
		GKeyFile* _tmp1_;
		const gchar* _tmp2_;
		_tmp1_ = file;
		_tmp2_ = self->priv->autostartfile;
		g_key_file_load_from_file (_tmp1_, _tmp2_, G_KEY_FILE_NONE, &_inner_error_);
		if (_inner_error_ != NULL) {
			goto __catch7_g_error;
		}
	}
	goto __finally7;
	__catch7_g_error:
	{
		GError* e = NULL;
		e = _inner_error_;
		_inner_error_ = NULL;
		result = FALSE;
		_g_error_free0 (e);
		_g_key_file_free0 (file);
		return result;
	}
	__finally7:
	if (_inner_error_ != NULL) {
		_g_key_file_free0 (file);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return FALSE;
	}
	{
		GKeyFile* _tmp3_;
		const gchar* _tmp4_;
		gboolean _tmp5_ = FALSE;
		gboolean _tmp6_;
		_tmp3_ = file;
		_tmp4_ = self->priv->autostartkey;
		_tmp5_ = g_key_file_get_boolean (_tmp3_, G_KEY_FILE_DESKTOP_GROUP, _tmp4_, &_inner_error_);
		_tmp6_ = _tmp5_;
		if (_inner_error_ != NULL) {
			goto __catch8_g_error;
		}
		result = _tmp6_;
		_g_key_file_free0 (file);
		return result;
	}
	goto __finally8;
	__catch8_g_error:
	{
		GError* e = NULL;
		e = _inner_error_;
		_inner_error_ = NULL;
		result = TRUE;
		_g_error_free0 (e);
		_g_key_file_free0 (file);
		return result;
	}
	__finally8:
	_g_key_file_free0 (file);
	g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
	g_clear_error (&_inner_error_);
	return FALSE;
}


void main_set_autostart (Main* self, gboolean value) {
	GKeyFile* _tmp0_;
	GKeyFile* file;
	const gchar* _tmp3_;
	gboolean _tmp4_;
	GError * _inner_error_ = NULL;
	g_return_if_fail (IS_MAIN (self));
	_tmp0_ = g_key_file_new ();
	file = _tmp0_;
	{
		const gchar* _tmp1_;
		_tmp1_ = self->priv->autostartfile;
		g_key_file_load_from_file (file, _tmp1_, G_KEY_FILE_KEEP_COMMENTS | G_KEY_FILE_KEEP_TRANSLATIONS, &_inner_error_);
		if (_inner_error_ != NULL) {
			goto __catch9_g_error;
		}
	}
	goto __finally9;
	__catch9_g_error:
	{
		GError* e = NULL;
		e = _inner_error_;
		_inner_error_ = NULL;
		{
			const gchar* _tmp2_;
			_tmp2_ = self->priv->applicationfile;
			g_key_file_load_from_data_dirs (file, _tmp2_, NULL, G_KEY_FILE_KEEP_COMMENTS | G_KEY_FILE_KEEP_TRANSLATIONS, &_inner_error_);
			if (_inner_error_ != NULL) {
				goto __catch10_g_error;
			}
		}
		goto __finally10;
		__catch10_g_error:
		{
			GError* e = NULL;
			e = _inner_error_;
			_inner_error_ = NULL;
			g_key_file_set_string (file, G_KEY_FILE_DESKTOP_GROUP, G_KEY_FILE_DESKTOP_KEY_TYPE, "Application");
			g_key_file_set_string (file, G_KEY_FILE_DESKTOP_GROUP, G_KEY_FILE_DESKTOP_KEY_NAME, "indicator-multiload");
			g_key_file_set_string (file, G_KEY_FILE_DESKTOP_GROUP, G_KEY_FILE_DESKTOP_KEY_EXEC, "indicator-multiload");
			_g_error_free0 (e);
		}
		__finally10:
		if (_inner_error_ != NULL) {
			_g_error_free0 (e);
			_g_error_free0 (e);
			_g_key_file_free0 (file);
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return;
		}
		_g_error_free0 (e);
	}
	__finally9:
	if (_inner_error_ != NULL) {
		_g_key_file_free0 (file);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_tmp3_ = self->priv->autostartkey;
	_tmp4_ = value;
	g_key_file_set_boolean (file, G_KEY_FILE_DESKTOP_GROUP, _tmp3_, _tmp4_);
	{
		const gchar* _tmp5_ = NULL;
		gchar* _tmp6_ = NULL;
		gchar* _tmp7_;
		const gchar* _tmp8_;
		gchar* _tmp9_ = NULL;
		gchar* _tmp10_;
		_tmp5_ = g_get_user_config_dir ();
		_tmp6_ = g_build_filename (_tmp5_, "autostart", NULL);
		_tmp7_ = _tmp6_;
		g_mkdir (_tmp7_, 0777);
		_g_free0 (_tmp7_);
		_tmp8_ = self->priv->autostartfile;
		_tmp9_ = g_key_file_to_data (file, NULL, NULL);
		_tmp10_ = _tmp9_;
		g_file_set_contents (_tmp8_, _tmp10_, (gssize) (-1), &_inner_error_);
		_g_free0 (_tmp10_);
		if (_inner_error_ != NULL) {
			goto __catch11_g_error;
		}
	}
	goto __finally11;
	__catch11_g_error:
	{
		GError* e = NULL;
		FILE* _tmp11_;
		GError* _tmp12_;
		const gchar* _tmp13_;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp11_ = stderr;
		_tmp12_ = e;
		_tmp13_ = _tmp12_->message;
		fprintf (_tmp11_, "Could not create autostart desktop file: %s\n", _tmp13_);
		_g_error_free0 (e);
	}
	__finally11:
	if (_inner_error_ != NULL) {
		_g_key_file_free0 (file);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_g_key_file_free0 (file);
	g_object_notify ((GObject *) self, "autostart");
}


static void main_class_init (MainClass * klass) {
	main_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (MainPrivate));
	G_APPLICATION_CLASS (klass)->activate = main_real_activate;
	G_APPLICATION_CLASS (klass)->startup = main_real_startup;
	G_APPLICATION_CLASS (klass)->command_line = main_real_command_line;
	G_APPLICATION_CLASS (klass)->local_command_line = main_real_local_command_line;
	G_OBJECT_CLASS (klass)->get_property = _vala_main_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_main_set_property;
	G_OBJECT_CLASS (klass)->finalize = main_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), MAIN_AUTOSTART, g_param_spec_boolean ("autostart", "autostart", "autostart", FALSE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
}


static void main_instance_init (Main * self) {
	self->priv = MAIN_GET_PRIVATE (self);
}


static void main_finalize (GObject* obj) {
	Main * self;
	MultiLoadIndicator* _tmp0_;
	self = MAIN (obj);
	_tmp0_ = self->priv->multi;
	if (_tmp0_ != NULL) {
		MultiLoadIndicator* _tmp1_;
		_tmp1_ = self->priv->multi;
		multi_load_indicator_destroy (_tmp1_);
	}
	_g_object_unref0 (self->priv->multi);
	_g_object_unref0 (self->priv->about);
	_g_object_unref0 (self->priv->preferences);
	_g_object_unref0 (self->priv->settingscache);
	_g_free0 (self->priv->autostartkey);
	_g_free0 (self->priv->desktopfilename);
	_g_free0 (self->priv->autostartfile);
	_g_free0 (self->priv->applicationfile);
	_g_free0 (self->priv->graphsetups);
	G_OBJECT_CLASS (main_parent_class)->finalize (obj);
}


/******************************************************************************
 * Copyright (C) 2011  Michael Hofmann <mh21@piware.de>                       *
 *                                                                            *
 * This program is free software; you can redistribute it and/or modify       *
 * it under the terms of the GNU General Public License as published by       *
 * the Free Software Foundation; either version 3 of the License, or          *
 * (at your option) any later version.                                        *
 *                                                                            *
 * This program is distributed in the hope that it will be useful,            *
 * but WITHOUT ANY WARRANTY; without even the implied warranty of             *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the              *
 * GNU General Public License for more details.                               *
 *                                                                            *
 * You should have received a copy of the GNU General Public License along    *
 * with this program; if not, write to the Free Software Foundation, Inc.,    *
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.                *
 ******************************************************************************/
GType main_get_type (void) {
	static volatile gsize main_type_id__volatile = 0;
	if (g_once_init_enter (&main_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (MainClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) main_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (Main), 0, (GInstanceInitFunc) main_instance_init, NULL };
		GType main_type_id;
		main_type_id = g_type_register_static (G_TYPE_APPLICATION, "Main", &g_define_type_info, 0);
		g_once_init_leave (&main_type_id__volatile, main_type_id);
	}
	return main_type_id__volatile;
}


static void _vala_main_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	Main * self;
	self = MAIN (object);
	switch (property_id) {
		case MAIN_AUTOSTART:
		g_value_set_boolean (value, main_get_autostart (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_main_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	Main * self;
	self = MAIN (object);
	switch (property_id) {
		case MAIN_AUTOSTART:
		main_set_autostart (self, g_value_get_boolean (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}


static gint _vala_array_length (gpointer array) {
	int length;
	length = 0;
	if (array) {
		while (((gpointer*) array)[length]) {
			length++;
		}
	}
	return length;
}



