/* settingsconversion.c generated by valac 0.14.2, the Vala compiler
 * generated from settingsconversion.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gio/gio.h>
#include <stdlib.h>
#include <string.h>


#define TYPE_SETTINGS_CONVERSION (settings_conversion_get_type ())
#define SETTINGS_CONVERSION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_SETTINGS_CONVERSION, SettingsConversion))
#define SETTINGS_CONVERSION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_SETTINGS_CONVERSION, SettingsConversionClass))
#define IS_SETTINGS_CONVERSION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_SETTINGS_CONVERSION))
#define IS_SETTINGS_CONVERSION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_SETTINGS_CONVERSION))
#define SETTINGS_CONVERSION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_SETTINGS_CONVERSION, SettingsConversionClass))

typedef struct _SettingsConversion SettingsConversion;
typedef struct _SettingsConversionClass SettingsConversionClass;
typedef struct _SettingsConversionPrivate SettingsConversionPrivate;

#define TYPE_SETTINGS_CACHE (settings_cache_get_type ())
#define SETTINGS_CACHE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_SETTINGS_CACHE, SettingsCache))
#define SETTINGS_CACHE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_SETTINGS_CACHE, SettingsCacheClass))
#define IS_SETTINGS_CACHE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_SETTINGS_CACHE))
#define IS_SETTINGS_CACHE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_SETTINGS_CACHE))
#define SETTINGS_CACHE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_SETTINGS_CACHE, SettingsCacheClass))

typedef struct _SettingsCache SettingsCache;
typedef struct _SettingsCacheClass SettingsCacheClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_variant_unref0(var) ((var == NULL) ? NULL : (var = (g_variant_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))

struct _SettingsConversion {
	GObject parent_instance;
	SettingsConversionPrivate * priv;
};

struct _SettingsConversionClass {
	GObjectClass parent_class;
};

struct _SettingsConversionPrivate {
	SettingsCache* settingscache;
};


static gpointer settings_conversion_parent_class = NULL;

GType settings_conversion_get_type (void) G_GNUC_CONST;
GType settings_cache_get_type (void) G_GNUC_CONST;
#define SETTINGS_CONVERSION_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_SETTINGS_CONVERSION, SettingsConversionPrivate))
enum  {
	SETTINGS_CONVERSION_DUMMY_PROPERTY
};
SettingsCache* settings_cache_new (void);
SettingsCache* settings_cache_construct (GType object_type);
guint settings_conversion_oldversion (SettingsConversion* self);
GSettings* settings_cache_generalsettings (SettingsCache* self);
gboolean settings_conversion_is_current (SettingsConversion* self);
void settings_conversion_convert (SettingsConversion* self);
static void settings_conversion_convert_version1 (SettingsConversion* self);
static GVariant* _variant_new1 (guint value);
GSettings* settings_cache_graphsettings (SettingsCache* self, const gchar* graphid);
GSettings* settings_cache_tracesettings (SettingsCache* self, const gchar* graphid, const gchar* traceid);
SettingsConversion* settings_conversion_new (void);
SettingsConversion* settings_conversion_construct (GType object_type);
static void settings_conversion_finalize (GObject* obj);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);
static gint _vala_array_length (gpointer array);


guint settings_conversion_oldversion (SettingsConversion* self) {
	guint result = 0U;
	SettingsCache* _tmp0_;
	GSettings* _tmp1_ = NULL;
	GSettings* settings;
	GVariant* _tmp2_ = NULL;
	GVariant* _tmp3_;
	guint32 _tmp4_ = 0U;
	guint _tmp5_;
	g_return_val_if_fail (IS_SETTINGS_CONVERSION (self), 0U);
	_tmp0_ = self->priv->settingscache;
	_tmp1_ = settings_cache_generalsettings (_tmp0_);
	settings = _tmp1_;
	_tmp2_ = g_settings_get_value (settings, "settings-version");
	_tmp3_ = _tmp2_;
	_tmp4_ = g_variant_get_uint32 (_tmp3_);
	_tmp5_ = (guint) _tmp4_;
	_g_variant_unref0 (_tmp3_);
	result = _tmp5_;
	_g_object_unref0 (settings);
	return result;
}


gboolean settings_conversion_is_current (SettingsConversion* self) {
	gboolean result = FALSE;
	guint _tmp0_ = 0U;
	g_return_val_if_fail (IS_SETTINGS_CONVERSION (self), FALSE);
	_tmp0_ = settings_conversion_oldversion (self);
	result = _tmp0_ == ((guint) 2);
	return result;
}


static GVariant* _variant_new1 (guint value) {
	return g_variant_ref_sink (g_variant_new_uint32 (value));
}


void settings_conversion_convert (SettingsConversion* self) {
	SettingsCache* _tmp0_;
	GSettings* _tmp1_ = NULL;
	GSettings* settings;
	g_return_if_fail (IS_SETTINGS_CONVERSION (self));
	_tmp0_ = self->priv->settingscache;
	_tmp1_ = settings_cache_generalsettings (_tmp0_);
	settings = _tmp1_;
	while (TRUE) {
		gboolean _tmp2_ = FALSE;
		guint _tmp3_ = 0U;
		GSettings* _tmp4_;
		guint _tmp5_ = 0U;
		GVariant* _tmp6_;
		_tmp2_ = settings_conversion_is_current (self);
		if (!(!_tmp2_)) {
			break;
		}
		_tmp3_ = settings_conversion_oldversion (self);
		switch (_tmp3_) {
			case 1:
			{
				settings_conversion_convert_version1 (self);
				break;
			}
			default:
			break;
		}
		_tmp4_ = settings;
		_tmp5_ = settings_conversion_oldversion (self);
		_tmp6_ = _variant_new1 (_tmp5_ + 1);
		g_settings_set_value (_tmp4_, "settings-version", _tmp6_);
	}
	_g_object_unref0 (settings);
}


static void settings_conversion_convert_version1 (SettingsConversion* self) {
	GSettings* _tmp0_;
	GSettings* oldsettings;
	GSettings* _tmp1_;
	gchar** _tmp2_;
	gchar** _tmp3_ = NULL;
	g_return_if_fail (IS_SETTINGS_CONVERSION (self));
	_tmp0_ = g_settings_new_with_path ("de.mh21.indicator.multiload.version1", "/apps/indicators/multiload/");
	oldsettings = _tmp0_;
	_tmp1_ = oldsettings;
	_tmp3_ = _tmp2_ = g_settings_list_keys (_tmp1_);
	{
		gchar** key_collection = NULL;
		gint key_collection_length1 = 0;
		gint _key_collection_size_ = 0;
		gint key_it = 0;
		key_collection = _tmp3_;
		key_collection_length1 = _vala_array_length (_tmp2_);
		for (key_it = 0; key_it < _vala_array_length (_tmp2_); key_it = key_it + 1) {
			gchar* _tmp4_;
			gchar* key = NULL;
			_tmp4_ = g_strdup (key_collection[key_it]);
			key = _tmp4_;
			{
				GSettings* _tmp5_;
				const gchar* _tmp6_;
				GVariant* _tmp7_ = NULL;
				GVariant* value;
				GSettings* _tmp8_;
				const gchar* _tmp9_;
				GSettings* _tmp10_;
				const gchar* _tmp11_;
				GVariant* _tmp12_ = NULL;
				GVariant* defaultvalue;
				GVariant* _tmp13_;
				GVariant* _tmp14_;
				gboolean _tmp15_ = FALSE;
				_tmp5_ = oldsettings;
				_tmp6_ = key;
				_tmp7_ = g_settings_get_value (_tmp5_, _tmp6_);
				value = _tmp7_;
				_tmp8_ = oldsettings;
				_tmp9_ = key;
				g_settings_reset (_tmp8_, _tmp9_);
				_tmp10_ = oldsettings;
				_tmp11_ = key;
				_tmp12_ = g_settings_get_value (_tmp10_, _tmp11_);
				defaultvalue = _tmp12_;
				_tmp13_ = value;
				_tmp14_ = defaultvalue;
				_tmp15_ = g_variant_equal (_tmp13_, _tmp14_);
				if (!_tmp15_) {
					const gchar* _tmp16_;
					const gchar* _tmp17_;
					GQuark _tmp19_ = 0U;
					static GQuark _tmp18_label0 = 0;
					static GQuark _tmp18_label1 = 0;
					static GQuark _tmp18_label2 = 0;
					static GQuark _tmp18_label3 = 0;
					static GQuark _tmp18_label4 = 0;
					static GQuark _tmp18_label5 = 0;
					static GQuark _tmp18_label6 = 0;
					static GQuark _tmp18_label7 = 0;
					static GQuark _tmp18_label8 = 0;
					static GQuark _tmp18_label9 = 0;
					static GQuark _tmp18_label10 = 0;
					static GQuark _tmp18_label11 = 0;
					static GQuark _tmp18_label12 = 0;
					static GQuark _tmp18_label13 = 0;
					static GQuark _tmp18_label14 = 0;
					static GQuark _tmp18_label15 = 0;
					static GQuark _tmp18_label16 = 0;
					static GQuark _tmp18_label17 = 0;
					static GQuark _tmp18_label18 = 0;
					static GQuark _tmp18_label19 = 0;
					static GQuark _tmp18_label20 = 0;
					static GQuark _tmp18_label21 = 0;
					static GQuark _tmp18_label22 = 0;
					static GQuark _tmp18_label23 = 0;
					static GQuark _tmp18_label24 = 0;
					static GQuark _tmp18_label25 = 0;
					static GQuark _tmp18_label26 = 0;
					static GQuark _tmp18_label27 = 0;
					static GQuark _tmp18_label28 = 0;
					static GQuark _tmp18_label29 = 0;
					static GQuark _tmp18_label30 = 0;
					static GQuark _tmp18_label31 = 0;
					static GQuark _tmp18_label32 = 0;
					static GQuark _tmp18_label33 = 0;
					static GQuark _tmp18_label34 = 0;
					static GQuark _tmp18_label35 = 0;
					static GQuark _tmp18_label36 = 0;
					static GQuark _tmp18_label37 = 0;
					_tmp16_ = key;
					_tmp17_ = _tmp16_;
					_tmp19_ = (NULL == _tmp17_) ? 0 : g_quark_from_string (_tmp17_);
					if (_tmp19_ == ((0 != _tmp18_label0) ? _tmp18_label0 : (_tmp18_label0 = g_quark_from_static_string ("cpuload-alpha4")))) {
						switch (0) {
							default:
							{
								SettingsCache* _tmp20_;
								GSettings* _tmp21_ = NULL;
								GSettings* _tmp22_;
								GVariant* _tmp23_;
								_tmp20_ = self->priv->settingscache;
								_tmp21_ = settings_cache_graphsettings (_tmp20_, "cpu");
								_tmp22_ = _tmp21_;
								_tmp23_ = value;
								g_settings_set_value (_tmp22_, "alpha", _tmp23_);
								_g_object_unref0 (_tmp22_);
								break;
							}
						}
					} else if (_tmp19_ == ((0 != _tmp18_label1) ? _tmp18_label1 : (_tmp18_label1 = g_quark_from_static_string ("memload-alpha4")))) {
						switch (0) {
							default:
							{
								SettingsCache* _tmp24_;
								GSettings* _tmp25_ = NULL;
								GSettings* _tmp26_;
								GVariant* _tmp27_;
								_tmp24_ = self->priv->settingscache;
								_tmp25_ = settings_cache_graphsettings (_tmp24_, "mem");
								_tmp26_ = _tmp25_;
								_tmp27_ = value;
								g_settings_set_value (_tmp26_, "alpha", _tmp27_);
								_g_object_unref0 (_tmp26_);
								break;
							}
						}
					} else if (_tmp19_ == ((0 != _tmp18_label2) ? _tmp18_label2 : (_tmp18_label2 = g_quark_from_static_string ("netload-alpha3")))) {
						switch (0) {
							default:
							{
								SettingsCache* _tmp28_;
								GSettings* _tmp29_ = NULL;
								GSettings* _tmp30_;
								GVariant* _tmp31_;
								_tmp28_ = self->priv->settingscache;
								_tmp29_ = settings_cache_graphsettings (_tmp28_, "net");
								_tmp30_ = _tmp29_;
								_tmp31_ = value;
								g_settings_set_value (_tmp30_, "alpha", _tmp31_);
								_g_object_unref0 (_tmp30_);
								break;
							}
						}
					} else if (_tmp19_ == ((0 != _tmp18_label3) ? _tmp18_label3 : (_tmp18_label3 = g_quark_from_static_string ("swapload-alpha1")))) {
						switch (0) {
							default:
							{
								SettingsCache* _tmp32_;
								GSettings* _tmp33_ = NULL;
								GSettings* _tmp34_;
								GVariant* _tmp35_;
								_tmp32_ = self->priv->settingscache;
								_tmp33_ = settings_cache_graphsettings (_tmp32_, "swap");
								_tmp34_ = _tmp33_;
								_tmp35_ = value;
								g_settings_set_value (_tmp34_, "alpha", _tmp35_);
								_g_object_unref0 (_tmp34_);
								break;
							}
						}
					} else if (_tmp19_ == ((0 != _tmp18_label4) ? _tmp18_label4 : (_tmp18_label4 = g_quark_from_static_string ("loadavg-alpha1")))) {
						switch (0) {
							default:
							{
								SettingsCache* _tmp36_;
								GSettings* _tmp37_ = NULL;
								GSettings* _tmp38_;
								GVariant* _tmp39_;
								_tmp36_ = self->priv->settingscache;
								_tmp37_ = settings_cache_graphsettings (_tmp36_, "load");
								_tmp38_ = _tmp37_;
								_tmp39_ = value;
								g_settings_set_value (_tmp38_, "alpha", _tmp39_);
								_g_object_unref0 (_tmp38_);
								break;
							}
						}
					} else if (_tmp19_ == ((0 != _tmp18_label5) ? _tmp18_label5 : (_tmp18_label5 = g_quark_from_static_string ("diskload-alpha2")))) {
						switch (0) {
							default:
							{
								SettingsCache* _tmp40_;
								GSettings* _tmp41_ = NULL;
								GSettings* _tmp42_;
								GVariant* _tmp43_;
								_tmp40_ = self->priv->settingscache;
								_tmp41_ = settings_cache_graphsettings (_tmp40_, "disk");
								_tmp42_ = _tmp41_;
								_tmp43_ = value;
								g_settings_set_value (_tmp42_, "alpha", _tmp43_);
								_g_object_unref0 (_tmp42_);
								break;
							}
						}
					} else if (_tmp19_ == ((0 != _tmp18_label6) ? _tmp18_label6 : (_tmp18_label6 = g_quark_from_static_string ("view-cpuload")))) {
						switch (0) {
							default:
							{
								SettingsCache* _tmp44_;
								GSettings* _tmp45_ = NULL;
								GSettings* _tmp46_;
								GVariant* _tmp47_;
								_tmp44_ = self->priv->settingscache;
								_tmp45_ = settings_cache_graphsettings (_tmp44_, "cpu");
								_tmp46_ = _tmp45_;
								_tmp47_ = value;
								g_settings_set_value (_tmp46_, "enabled", _tmp47_);
								_g_object_unref0 (_tmp46_);
								break;
							}
						}
					} else if (_tmp19_ == ((0 != _tmp18_label7) ? _tmp18_label7 : (_tmp18_label7 = g_quark_from_static_string ("view-memload")))) {
						switch (0) {
							default:
							{
								SettingsCache* _tmp48_;
								GSettings* _tmp49_ = NULL;
								GSettings* _tmp50_;
								GVariant* _tmp51_;
								_tmp48_ = self->priv->settingscache;
								_tmp49_ = settings_cache_graphsettings (_tmp48_, "mem");
								_tmp50_ = _tmp49_;
								_tmp51_ = value;
								g_settings_set_value (_tmp50_, "enabled", _tmp51_);
								_g_object_unref0 (_tmp50_);
								break;
							}
						}
					} else if (_tmp19_ == ((0 != _tmp18_label8) ? _tmp18_label8 : (_tmp18_label8 = g_quark_from_static_string ("view-netload")))) {
						switch (0) {
							default:
							{
								SettingsCache* _tmp52_;
								GSettings* _tmp53_ = NULL;
								GSettings* _tmp54_;
								GVariant* _tmp55_;
								_tmp52_ = self->priv->settingscache;
								_tmp53_ = settings_cache_graphsettings (_tmp52_, "net");
								_tmp54_ = _tmp53_;
								_tmp55_ = value;
								g_settings_set_value (_tmp54_, "enabled", _tmp55_);
								_g_object_unref0 (_tmp54_);
								break;
							}
						}
					} else if (_tmp19_ == ((0 != _tmp18_label9) ? _tmp18_label9 : (_tmp18_label9 = g_quark_from_static_string ("view-swapload")))) {
						switch (0) {
							default:
							{
								SettingsCache* _tmp56_;
								GSettings* _tmp57_ = NULL;
								GSettings* _tmp58_;
								GVariant* _tmp59_;
								_tmp56_ = self->priv->settingscache;
								_tmp57_ = settings_cache_graphsettings (_tmp56_, "swap");
								_tmp58_ = _tmp57_;
								_tmp59_ = value;
								g_settings_set_value (_tmp58_, "enabled", _tmp59_);
								_g_object_unref0 (_tmp58_);
								break;
							}
						}
					} else if (_tmp19_ == ((0 != _tmp18_label10) ? _tmp18_label10 : (_tmp18_label10 = g_quark_from_static_string ("view-loadavg")))) {
						switch (0) {
							default:
							{
								SettingsCache* _tmp60_;
								GSettings* _tmp61_ = NULL;
								GSettings* _tmp62_;
								GVariant* _tmp63_;
								_tmp60_ = self->priv->settingscache;
								_tmp61_ = settings_cache_graphsettings (_tmp60_, "load");
								_tmp62_ = _tmp61_;
								_tmp63_ = value;
								g_settings_set_value (_tmp62_, "enabled", _tmp63_);
								_g_object_unref0 (_tmp62_);
								break;
							}
						}
					} else if (_tmp19_ == ((0 != _tmp18_label11) ? _tmp18_label11 : (_tmp18_label11 = g_quark_from_static_string ("view-diskload")))) {
						switch (0) {
							default:
							{
								SettingsCache* _tmp64_;
								GSettings* _tmp65_ = NULL;
								GSettings* _tmp66_;
								GVariant* _tmp67_;
								_tmp64_ = self->priv->settingscache;
								_tmp65_ = settings_cache_graphsettings (_tmp64_, "disk");
								_tmp66_ = _tmp65_;
								_tmp67_ = value;
								g_settings_set_value (_tmp66_, "enabled", _tmp67_);
								_g_object_unref0 (_tmp66_);
								break;
							}
						}
					} else if (_tmp19_ == ((0 != _tmp18_label12) ? _tmp18_label12 : (_tmp18_label12 = g_quark_from_static_string ("cpuload-color0")))) {
						switch (0) {
							default:
							{
								SettingsCache* _tmp68_;
								GSettings* _tmp69_ = NULL;
								GSettings* _tmp70_;
								GVariant* _tmp71_;
								_tmp68_ = self->priv->settingscache;
								_tmp69_ = settings_cache_tracesettings (_tmp68_, "cpu", "cpu1");
								_tmp70_ = _tmp69_;
								_tmp71_ = value;
								g_settings_set_value (_tmp70_, "color", _tmp71_);
								_g_object_unref0 (_tmp70_);
								break;
							}
						}
					} else if (_tmp19_ == ((0 != _tmp18_label13) ? _tmp18_label13 : (_tmp18_label13 = g_quark_from_static_string ("cpuload-color1")))) {
						switch (0) {
							default:
							{
								SettingsCache* _tmp72_;
								GSettings* _tmp73_ = NULL;
								GSettings* _tmp74_;
								GVariant* _tmp75_;
								_tmp72_ = self->priv->settingscache;
								_tmp73_ = settings_cache_tracesettings (_tmp72_, "cpu", "cpu2");
								_tmp74_ = _tmp73_;
								_tmp75_ = value;
								g_settings_set_value (_tmp74_, "color", _tmp75_);
								_g_object_unref0 (_tmp74_);
								break;
							}
						}
					} else if (_tmp19_ == ((0 != _tmp18_label14) ? _tmp18_label14 : (_tmp18_label14 = g_quark_from_static_string ("cpuload-color2")))) {
						switch (0) {
							default:
							{
								SettingsCache* _tmp76_;
								GSettings* _tmp77_ = NULL;
								GSettings* _tmp78_;
								GVariant* _tmp79_;
								_tmp76_ = self->priv->settingscache;
								_tmp77_ = settings_cache_tracesettings (_tmp76_, "cpu", "cpu3");
								_tmp78_ = _tmp77_;
								_tmp79_ = value;
								g_settings_set_value (_tmp78_, "color", _tmp79_);
								_g_object_unref0 (_tmp78_);
								break;
							}
						}
					} else if (_tmp19_ == ((0 != _tmp18_label15) ? _tmp18_label15 : (_tmp18_label15 = g_quark_from_static_string ("cpuload-color3")))) {
						switch (0) {
							default:
							{
								SettingsCache* _tmp80_;
								GSettings* _tmp81_ = NULL;
								GSettings* _tmp82_;
								GVariant* _tmp83_;
								_tmp80_ = self->priv->settingscache;
								_tmp81_ = settings_cache_tracesettings (_tmp80_, "cpu", "cpu4");
								_tmp82_ = _tmp81_;
								_tmp83_ = value;
								g_settings_set_value (_tmp82_, "color", _tmp83_);
								_g_object_unref0 (_tmp82_);
								break;
							}
						}
					} else if (_tmp19_ == ((0 != _tmp18_label16) ? _tmp18_label16 : (_tmp18_label16 = g_quark_from_static_string ("cpuload-color4")))) {
						switch (0) {
							default:
							{
								SettingsCache* _tmp84_;
								GSettings* _tmp85_ = NULL;
								GSettings* _tmp86_;
								GVariant* _tmp87_;
								_tmp84_ = self->priv->settingscache;
								_tmp85_ = settings_cache_graphsettings (_tmp84_, "cpu");
								_tmp86_ = _tmp85_;
								_tmp87_ = value;
								g_settings_set_value (_tmp86_, "background-color", _tmp87_);
								_g_object_unref0 (_tmp86_);
								break;
							}
						}
					} else if (_tmp19_ == ((0 != _tmp18_label17) ? _tmp18_label17 : (_tmp18_label17 = g_quark_from_static_string ("memload-color0")))) {
						switch (0) {
							default:
							{
								SettingsCache* _tmp88_;
								GSettings* _tmp89_ = NULL;
								GSettings* _tmp90_;
								GVariant* _tmp91_;
								_tmp88_ = self->priv->settingscache;
								_tmp89_ = settings_cache_tracesettings (_tmp88_, "mem", "mem1");
								_tmp90_ = _tmp89_;
								_tmp91_ = value;
								g_settings_set_value (_tmp90_, "color", _tmp91_);
								_g_object_unref0 (_tmp90_);
								break;
							}
						}
					} else if (_tmp19_ == ((0 != _tmp18_label18) ? _tmp18_label18 : (_tmp18_label18 = g_quark_from_static_string ("memload-color1")))) {
						switch (0) {
							default:
							{
								SettingsCache* _tmp92_;
								GSettings* _tmp93_ = NULL;
								GSettings* _tmp94_;
								GVariant* _tmp95_;
								_tmp92_ = self->priv->settingscache;
								_tmp93_ = settings_cache_tracesettings (_tmp92_, "mem", "mem2");
								_tmp94_ = _tmp93_;
								_tmp95_ = value;
								g_settings_set_value (_tmp94_, "color", _tmp95_);
								_g_object_unref0 (_tmp94_);
								break;
							}
						}
					} else if (_tmp19_ == ((0 != _tmp18_label19) ? _tmp18_label19 : (_tmp18_label19 = g_quark_from_static_string ("memload-color2")))) {
						switch (0) {
							default:
							{
								SettingsCache* _tmp96_;
								GSettings* _tmp97_ = NULL;
								GSettings* _tmp98_;
								GVariant* _tmp99_;
								_tmp96_ = self->priv->settingscache;
								_tmp97_ = settings_cache_tracesettings (_tmp96_, "mem", "mem3");
								_tmp98_ = _tmp97_;
								_tmp99_ = value;
								g_settings_set_value (_tmp98_, "color", _tmp99_);
								_g_object_unref0 (_tmp98_);
								break;
							}
						}
					} else if (_tmp19_ == ((0 != _tmp18_label20) ? _tmp18_label20 : (_tmp18_label20 = g_quark_from_static_string ("memload-color3")))) {
						switch (0) {
							default:
							{
								SettingsCache* _tmp100_;
								GSettings* _tmp101_ = NULL;
								GSettings* _tmp102_;
								GVariant* _tmp103_;
								_tmp100_ = self->priv->settingscache;
								_tmp101_ = settings_cache_tracesettings (_tmp100_, "mem", "mem4");
								_tmp102_ = _tmp101_;
								_tmp103_ = value;
								g_settings_set_value (_tmp102_, "color", _tmp103_);
								_g_object_unref0 (_tmp102_);
								break;
							}
						}
					} else if (_tmp19_ == ((0 != _tmp18_label21) ? _tmp18_label21 : (_tmp18_label21 = g_quark_from_static_string ("memload-color4")))) {
						switch (0) {
							default:
							{
								SettingsCache* _tmp104_;
								GSettings* _tmp105_ = NULL;
								GSettings* _tmp106_;
								GVariant* _tmp107_;
								_tmp104_ = self->priv->settingscache;
								_tmp105_ = settings_cache_graphsettings (_tmp104_, "mem");
								_tmp106_ = _tmp105_;
								_tmp107_ = value;
								g_settings_set_value (_tmp106_, "background-color", _tmp107_);
								_g_object_unref0 (_tmp106_);
								break;
							}
						}
					} else if (_tmp19_ == ((0 != _tmp18_label22) ? _tmp18_label22 : (_tmp18_label22 = g_quark_from_static_string ("netload-color0")))) {
						switch (0) {
							default:
							{
								SettingsCache* _tmp108_;
								GSettings* _tmp109_ = NULL;
								GSettings* _tmp110_;
								GVariant* _tmp111_;
								_tmp108_ = self->priv->settingscache;
								_tmp109_ = settings_cache_tracesettings (_tmp108_, "net", "net1");
								_tmp110_ = _tmp109_;
								_tmp111_ = value;
								g_settings_set_value (_tmp110_, "color", _tmp111_);
								_g_object_unref0 (_tmp110_);
								break;
							}
						}
					} else if (_tmp19_ == ((0 != _tmp18_label23) ? _tmp18_label23 : (_tmp18_label23 = g_quark_from_static_string ("netload-color1")))) {
						switch (0) {
							default:
							{
								SettingsCache* _tmp112_;
								GSettings* _tmp113_ = NULL;
								GSettings* _tmp114_;
								GVariant* _tmp115_;
								_tmp112_ = self->priv->settingscache;
								_tmp113_ = settings_cache_tracesettings (_tmp112_, "net", "net2");
								_tmp114_ = _tmp113_;
								_tmp115_ = value;
								g_settings_set_value (_tmp114_, "color", _tmp115_);
								_g_object_unref0 (_tmp114_);
								break;
							}
						}
					} else if (_tmp19_ == ((0 != _tmp18_label24) ? _tmp18_label24 : (_tmp18_label24 = g_quark_from_static_string ("netload-color2")))) {
						switch (0) {
							default:
							{
								SettingsCache* _tmp116_;
								GSettings* _tmp117_ = NULL;
								GSettings* _tmp118_;
								GVariant* _tmp119_;
								_tmp116_ = self->priv->settingscache;
								_tmp117_ = settings_cache_tracesettings (_tmp116_, "net", "net3");
								_tmp118_ = _tmp117_;
								_tmp119_ = value;
								g_settings_set_value (_tmp118_, "color", _tmp119_);
								_g_object_unref0 (_tmp118_);
								break;
							}
						}
					} else if (_tmp19_ == ((0 != _tmp18_label25) ? _tmp18_label25 : (_tmp18_label25 = g_quark_from_static_string ("netload-color3")))) {
						switch (0) {
							default:
							{
								SettingsCache* _tmp120_;
								GSettings* _tmp121_ = NULL;
								GSettings* _tmp122_;
								GVariant* _tmp123_;
								_tmp120_ = self->priv->settingscache;
								_tmp121_ = settings_cache_graphsettings (_tmp120_, "net");
								_tmp122_ = _tmp121_;
								_tmp123_ = value;
								g_settings_set_value (_tmp122_, "background-color", _tmp123_);
								_g_object_unref0 (_tmp122_);
								break;
							}
						}
					} else if (_tmp19_ == ((0 != _tmp18_label26) ? _tmp18_label26 : (_tmp18_label26 = g_quark_from_static_string ("swapload-color0")))) {
						switch (0) {
							default:
							{
								SettingsCache* _tmp124_;
								GSettings* _tmp125_ = NULL;
								GSettings* _tmp126_;
								GVariant* _tmp127_;
								_tmp124_ = self->priv->settingscache;
								_tmp125_ = settings_cache_tracesettings (_tmp124_, "swap", "swap1");
								_tmp126_ = _tmp125_;
								_tmp127_ = value;
								g_settings_set_value (_tmp126_, "color", _tmp127_);
								_g_object_unref0 (_tmp126_);
								break;
							}
						}
					} else if (_tmp19_ == ((0 != _tmp18_label27) ? _tmp18_label27 : (_tmp18_label27 = g_quark_from_static_string ("swapload-color1")))) {
						switch (0) {
							default:
							{
								SettingsCache* _tmp128_;
								GSettings* _tmp129_ = NULL;
								GSettings* _tmp130_;
								GVariant* _tmp131_;
								_tmp128_ = self->priv->settingscache;
								_tmp129_ = settings_cache_graphsettings (_tmp128_, "swap");
								_tmp130_ = _tmp129_;
								_tmp131_ = value;
								g_settings_set_value (_tmp130_, "background-color", _tmp131_);
								_g_object_unref0 (_tmp130_);
								break;
							}
						}
					} else if (_tmp19_ == ((0 != _tmp18_label28) ? _tmp18_label28 : (_tmp18_label28 = g_quark_from_static_string ("loadavg-color0")))) {
						switch (0) {
							default:
							{
								SettingsCache* _tmp132_;
								GSettings* _tmp133_ = NULL;
								GSettings* _tmp134_;
								GVariant* _tmp135_;
								_tmp132_ = self->priv->settingscache;
								_tmp133_ = settings_cache_tracesettings (_tmp132_, "load", "load1");
								_tmp134_ = _tmp133_;
								_tmp135_ = value;
								g_settings_set_value (_tmp134_, "color", _tmp135_);
								_g_object_unref0 (_tmp134_);
								break;
							}
						}
					} else if (_tmp19_ == ((0 != _tmp18_label29) ? _tmp18_label29 : (_tmp18_label29 = g_quark_from_static_string ("loadavg-color1")))) {
						switch (0) {
							default:
							{
								SettingsCache* _tmp136_;
								GSettings* _tmp137_ = NULL;
								GSettings* _tmp138_;
								GVariant* _tmp139_;
								_tmp136_ = self->priv->settingscache;
								_tmp137_ = settings_cache_graphsettings (_tmp136_, "load");
								_tmp138_ = _tmp137_;
								_tmp139_ = value;
								g_settings_set_value (_tmp138_, "background-color", _tmp139_);
								_g_object_unref0 (_tmp138_);
								break;
							}
						}
					} else if (_tmp19_ == ((0 != _tmp18_label30) ? _tmp18_label30 : (_tmp18_label30 = g_quark_from_static_string ("diskload-color0")))) {
						switch (0) {
							default:
							{
								SettingsCache* _tmp140_;
								GSettings* _tmp141_ = NULL;
								GSettings* _tmp142_;
								GVariant* _tmp143_;
								_tmp140_ = self->priv->settingscache;
								_tmp141_ = settings_cache_tracesettings (_tmp140_, "disk", "disk1");
								_tmp142_ = _tmp141_;
								_tmp143_ = value;
								g_settings_set_value (_tmp142_, "color", _tmp143_);
								_g_object_unref0 (_tmp142_);
								break;
							}
						}
					} else if (_tmp19_ == ((0 != _tmp18_label31) ? _tmp18_label31 : (_tmp18_label31 = g_quark_from_static_string ("diskload-color1")))) {
						switch (0) {
							default:
							{
								SettingsCache* _tmp144_;
								GSettings* _tmp145_ = NULL;
								GSettings* _tmp146_;
								GVariant* _tmp147_;
								_tmp144_ = self->priv->settingscache;
								_tmp145_ = settings_cache_tracesettings (_tmp144_, "disk", "disk2");
								_tmp146_ = _tmp145_;
								_tmp147_ = value;
								g_settings_set_value (_tmp146_, "color", _tmp147_);
								_g_object_unref0 (_tmp146_);
								break;
							}
						}
					} else if (_tmp19_ == ((0 != _tmp18_label32) ? _tmp18_label32 : (_tmp18_label32 = g_quark_from_static_string ("diskload-color2")))) {
						switch (0) {
							default:
							{
								SettingsCache* _tmp148_;
								GSettings* _tmp149_ = NULL;
								GSettings* _tmp150_;
								GVariant* _tmp151_;
								_tmp148_ = self->priv->settingscache;
								_tmp149_ = settings_cache_graphsettings (_tmp148_, "disk");
								_tmp150_ = _tmp149_;
								_tmp151_ = value;
								g_settings_set_value (_tmp150_, "background-color", _tmp151_);
								_g_object_unref0 (_tmp150_);
								break;
							}
						}
					} else if (_tmp19_ == ((0 != _tmp18_label33) ? _tmp18_label33 : (_tmp18_label33 = g_quark_from_static_string ("speed")))) {
						switch (0) {
							default:
							{
								SettingsCache* _tmp152_;
								GSettings* _tmp153_ = NULL;
								GSettings* _tmp154_;
								GVariant* _tmp155_;
								_tmp152_ = self->priv->settingscache;
								_tmp153_ = settings_cache_generalsettings (_tmp152_);
								_tmp154_ = _tmp153_;
								_tmp155_ = value;
								g_settings_set_value (_tmp154_, "speed", _tmp155_);
								_g_object_unref0 (_tmp154_);
								break;
							}
						}
					} else if (_tmp19_ == ((0 != _tmp18_label34) ? _tmp18_label34 : (_tmp18_label34 = g_quark_from_static_string ("size")))) {
						switch (0) {
							default:
							{
								SettingsCache* _tmp156_;
								GSettings* _tmp157_ = NULL;
								GSettings* _tmp158_;
								GVariant* _tmp159_;
								_tmp156_ = self->priv->settingscache;
								_tmp157_ = settings_cache_generalsettings (_tmp156_);
								_tmp158_ = _tmp157_;
								_tmp159_ = value;
								g_settings_set_value (_tmp158_, "width", _tmp159_);
								_g_object_unref0 (_tmp158_);
								break;
							}
						}
					} else if (_tmp19_ == ((0 != _tmp18_label35) ? _tmp18_label35 : (_tmp18_label35 = g_quark_from_static_string ("height")))) {
						switch (0) {
							default:
							{
								SettingsCache* _tmp160_;
								GSettings* _tmp161_ = NULL;
								GSettings* _tmp162_;
								GVariant* _tmp163_;
								_tmp160_ = self->priv->settingscache;
								_tmp161_ = settings_cache_generalsettings (_tmp160_);
								_tmp162_ = _tmp161_;
								_tmp163_ = value;
								g_settings_set_value (_tmp162_, "height", _tmp163_);
								_g_object_unref0 (_tmp162_);
								break;
							}
						}
					} else if (_tmp19_ == ((0 != _tmp18_label36) ? _tmp18_label36 : (_tmp18_label36 = g_quark_from_static_string ("system-monitor")))) {
						switch (0) {
							default:
							{
								SettingsCache* _tmp164_;
								GSettings* _tmp165_ = NULL;
								GSettings* _tmp166_;
								GVariant* _tmp167_;
								_tmp164_ = self->priv->settingscache;
								_tmp165_ = settings_cache_generalsettings (_tmp164_);
								_tmp166_ = _tmp165_;
								_tmp167_ = value;
								g_settings_set_value (_tmp166_, "system-monitor", _tmp167_);
								_g_object_unref0 (_tmp166_);
								break;
							}
						}
					} else if (_tmp19_ == ((0 != _tmp18_label37) ? _tmp18_label37 : (_tmp18_label37 = g_quark_from_static_string ("autostart")))) {
						switch (0) {
							default:
							{
								SettingsCache* _tmp168_;
								GSettings* _tmp169_ = NULL;
								GSettings* _tmp170_;
								GVariant* _tmp171_;
								_tmp168_ = self->priv->settingscache;
								_tmp169_ = settings_cache_generalsettings (_tmp168_);
								_tmp170_ = _tmp169_;
								_tmp171_ = value;
								g_settings_set_value (_tmp170_, "autostart", _tmp171_);
								_g_object_unref0 (_tmp170_);
								break;
							}
						}
					}
				}
				_g_variant_unref0 (defaultvalue);
				_g_variant_unref0 (value);
				_g_free0 (key);
			}
		}
		key_collection = (_vala_array_free (key_collection, key_collection_length1, (GDestroyNotify) g_free), NULL);
	}
	_g_object_unref0 (oldsettings);
}


SettingsConversion* settings_conversion_construct (GType object_type) {
	SettingsConversion * self = NULL;
	self = (SettingsConversion*) g_object_new (object_type, NULL);
	return self;
}


SettingsConversion* settings_conversion_new (void) {
	return settings_conversion_construct (TYPE_SETTINGS_CONVERSION);
}


static void settings_conversion_class_init (SettingsConversionClass * klass) {
	settings_conversion_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (SettingsConversionPrivate));
	G_OBJECT_CLASS (klass)->finalize = settings_conversion_finalize;
}


static void settings_conversion_instance_init (SettingsConversion * self) {
	SettingsCache* _tmp0_;
	self->priv = SETTINGS_CONVERSION_GET_PRIVATE (self);
	_tmp0_ = settings_cache_new ();
	self->priv->settingscache = _tmp0_;
}


static void settings_conversion_finalize (GObject* obj) {
	SettingsConversion * self;
	self = SETTINGS_CONVERSION (obj);
	_g_object_unref0 (self->priv->settingscache);
	G_OBJECT_CLASS (settings_conversion_parent_class)->finalize (obj);
}


/******************************************************************************
 * Copyright (C) 2011  Michael Hofmann <mh21@piware.de>                       *
 *                                                                            *
 * This program is free software; you can redistribute it and/or modify       *
 * it under the terms of the GNU General Public License as published by       *
 * the Free Software Foundation; either version 3 of the License, or          *
 * (at your option) any later version.                                        *
 *                                                                            *
 * This program is distributed in the hope that it will be useful,            *
 * but WITHOUT ANY WARRANTY; without even the implied warranty of             *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the              *
 * GNU General Public License for more details.                               *
 *                                                                            *
 * You should have received a copy of the GNU General Public License along    *
 * with this program; if not, write to the Free Software Foundation, Inc.,    *
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.                *
 ******************************************************************************/
GType settings_conversion_get_type (void) {
	static volatile gsize settings_conversion_type_id__volatile = 0;
	if (g_once_init_enter (&settings_conversion_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (SettingsConversionClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) settings_conversion_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (SettingsConversion), 0, (GInstanceInitFunc) settings_conversion_instance_init, NULL };
		GType settings_conversion_type_id;
		settings_conversion_type_id = g_type_register_static (G_TYPE_OBJECT, "SettingsConversion", &g_define_type_info, 0);
		g_once_init_leave (&settings_conversion_type_id__volatile, settings_conversion_type_id);
	}
	return settings_conversion_type_id__volatile;
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}


static gint _vala_array_length (gpointer array) {
	int length;
	length = 0;
	if (array) {
		while (((gpointer*) array)[length]) {
			length++;
		}
	}
	return length;
}



